# Generated by Django 6.1.1 on 2026-10-01 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('text', models.CharField(blank=True, default='', max_length=60)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('audience', models.CharField(choices=[('followers', 'Followers'), ('close_friends', 'Close friends')], default='followers', max_length=20)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='request_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('declined', 'Declined')], default='accepted', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='delete_after_seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='disappearing_messages_duration',
            field=models.CharField(choices=[('none', 'Off'), ('1_month', '1 Month'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('after_seen', 'After seen')], db_index=True, default='6_months', max_length=10),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', 'request_status'], name='cp_user_request_status_idx'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usernote',
            index=models.Index(fields=['expires_at'], name='usernote_expires_idx'),
        ),
    ]
