# Generated by Django 6.0.6 on 2026-09-14 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='revisiondeck',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash__gt', '')), fields=('conversation', 'session_id', 'content_hash'), name='uniq_revisiondeck_conv_session_hash_nonblank'),
        ),
    ]
