# Generated by Django 6.0.6 on 2026-08-03 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_studyroomstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='disappearing_messages_duration',
            field=models.CharField(choices=[('none', 'Off'), ('1_month', '1 Month'), ('6_months', '6 Months'), ('1_year', '1 Year')], db_index=True, default='6_months', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expires_at'], name='message_mes_expires_544b97_idx'),
        ),
    ]
