# Generated by Django 6.0.6 on 2026-08-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_conversationparticipant_label_groupjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='daily_message_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='message_permission',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('admins_mods', 'Admins & Moderators only')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='background_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
