# Generated by Django 6.0.6 on 2026-08-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_group_daily_message_limit_group_message_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='background_url',
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='wallpaper_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
