# Generated by Django 6.0.6 on 2026-08-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_remove_message_background_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparticipant',
            name='wallpaper_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
