# Generated by Django 6.0.6 on 2026-08-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_group_call_permission_group_study_room_permission_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pinnedmessage',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='pinnedmessage',
            name='message_pin_convers_7bcf85_idx',
        ),
        migrations.RemoveIndex(
            model_name='poll',
            name='message_pol_message_28645a_idx',
        ),
        migrations.RemoveIndex(
            model_name='polloption',
            name='message_pol_poll_id_5ab4b9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='pollvote',
            name='message_pol_option__242be2_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduledmessage',
            name='message_sch_is_sent_9d3094_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduledmessage',
            name='message_sch_sender__fac789_idx',
        ),
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='wallpaper_url',
        ),
        migrations.RemoveField(
            model_name='group',
            name='call_permission',
        ),
        migrations.RemoveField(
            model_name='group',
            name='daily_message_limit',
        ),
        migrations.RemoveField(
            model_name='group',
            name='message_permission',
        ),
        migrations.RemoveField(
            model_name='group',
            name='study_room_permission',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('presentation', 'Presentation'), ('location', 'Location'), ('system', 'System Message')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='groupmedia',
            name='file_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('presentation', 'Presentation'), ('location', 'Location'), ('system', 'System Message')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('presentation', 'Presentation'), ('location', 'Location'), ('system', 'System Message')], db_index=True, default='text', max_length=20),
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='message',
        ),
        migrations.RemoveField(
            model_name='polloption',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='option',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='sent_message',
        ),
        migrations.DeleteModel(
            name='PinnedMessage',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollOption',
        ),
        migrations.DeleteModel(
            name='PollVote',
        ),
        migrations.DeleteModel(
            name='ScheduledMessage',
        ),
    ]
