# Generated by Django 6.0.6 on 2026-08-30 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_alter_pinnedmessage_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='call_permission',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('admins_only', 'Admins/Moderators Only')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='daily_message_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='message_permission',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('admins_only', 'Admins/Moderators Only')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='study_room_permission',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('admins_only', 'Admins/Moderators Only')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_scheduled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('presentation', 'Presentation'), ('location', 'Location'), ('system', 'System Message'), ('study_room', 'Study Room Invite')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='groupmedia',
            name='file_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('presentation', 'Presentation'), ('location', 'Location'), ('system', 'System Message'), ('study_room', 'Study Room Invite')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('presentation', 'Presentation'), ('location', 'Location'), ('system', 'System Message'), ('study_room', 'Study Room Invite')], db_index=True, default='text', max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_pinned'], name='message_mes_convers_1f49ad_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_scheduled', 'scheduled_for'], name='message_mes_is_sche_82924d_idx'),
        ),
    ]
