# Generated by Django 6.0.6 on 2026-08-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0900_message_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encryption_iv',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
