# Generated by Django 6.0.6 on 2026-09-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0901_message_encryption_iv_message_is_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='wallpaper_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
