# Generated by Django 6.0.6 on 2026-09-06 11:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0903_remove_callsession_legacy_agora_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allow_anonymous_doubts',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_assignments', to='message.group')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='message.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassTranscriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('session_id', models.CharField(db_index=True, max_length=150)),
                ('start_offset_seconds', models.FloatField()),
                ('end_offset_seconds', models.FloatField()),
                ('audio_file_url', models.URLField(max_length=500)),
                ('text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_segments', to='message.conversation')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session_id', 'start_offset_seconds'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoubtQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('text', models.TextField(max_length=2000)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_revealed', models.BooleanField(default=False)),
                ('upvotes_count', models.PositiveIntegerField(default=0)),
                ('is_answered', models.BooleanField(default=False)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubts_answered', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts_asked', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='message.conversation')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='message.group')),
            ],
            options={
                'ordering': ['-upvotes_count', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoubtUpvote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='message.doubtquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('exception_rule', models.CharField(choices=[('teachers_only', 'Only teachers/staff'), ('nobody', 'Nobody — full silence')], default='teachers_only', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentAccessCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_revealed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_access_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('parent_access_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='message.parentaccesscode')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevisionDeck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('flashcards', models.JSONField(blank=True, default=list)),
                ('quiz', models.JSONField(blank=True, default=list)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_decks', to='message.conversation')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyRoomAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('session_id', models.CharField(blank=True, default='', max_length=150)),
                ('attended_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_room_attendances', to='message.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_room_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['group', 'due_at'], name='message_ass_group_i_af8f26_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student', 'is_submitted'], name='message_ass_student_239e12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='classtranscriptsegment',
            index=models.Index(fields=['conversation', 'session_id', 'start_offset_seconds'], name='message_cla_convers_9bbf08_idx'),
        ),
        migrations.AddIndex(
            model_name='classtranscriptsegment',
            index=models.Index(fields=['conversation', 'status'], name='message_cla_convers_cd5323_idx'),
        ),
        migrations.AddIndex(
            model_name='doubtquestion',
            index=models.Index(fields=['group', 'is_answered', '-upvotes_count'], name='message_dou_group_i_572665_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doubtupvote',
            unique_together={('doubt', 'user')},
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', 'ends_at'], name='message_foc_user_id_d07e44_idx'),
        ),
        migrations.AddIndex(
            model_name='parentaccesscode',
            index=models.Index(fields=['student', 'is_active'], name='message_par_student_fe57eb_idx'),
        ),
        migrations.AddIndex(
            model_name='parentaccesscode',
            index=models.Index(fields=['is_active', 'expires_at'], name='message_par_is_acti_6dcfec_idx'),
        ),
        migrations.AddIndex(
            model_name='revisiondeck',
            index=models.Index(fields=['conversation', '-created_at'], name='message_rev_convers_ae4034_idx'),
        ),
        migrations.AddIndex(
            model_name='studyroomattendance',
            index=models.Index(fields=['conversation', 'user', '-attended_date'], name='message_stu_convers_9e0008_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyroomattendance',
            constraint=models.UniqueConstraint(fields=('conversation', 'user', 'attended_date'), name='unique_study_room_attendance_per_day'),
        ),
    ]
