# Generated by Django 6.0.6 on 2026-09-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0904_group_allow_anonymous_doubts_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_announcement',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
