# """
# Django settings for LearnScroll project.
#
# Generated by 'django-admin startproject' using Django 6.0.6.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """
#
# from pathlib import Path
# import os
# from dotenv import load_dotenv
# from urllib.parse import urlparse
#
# BASE_DIR = Path(__file__).resolve().parent.parent
#
# load_dotenv(BASE_DIR / ".env")
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
#
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# # SECRET_KEY = 'django-insecure-=3#kh$fx$w*-ds==gl98&8+vcsjl=e2!*1^7gg9(l&c%ujhl7s'
# SECRET_KEY = os.getenv("SECRET_KEY")
# # SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = os.getenv("DEBUG", "False") == "True"
# DEBUG=True
# ALLOWED_HOSTS = ['*','10.93.221.189', 'localhost', '127.0.0.1']
#
#
# # Application definition
#
# INSTALLED_APPS = [
#     'daphne',
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'django_filters',
#     "rest_framework",
#     "drf_spectacular",
#     'corsheaders',
#     'login',
#     'user_profile',
#     'post',
#     "message",
# ]
#
# MIDDLEWARE = [
#     "corsheaders.middleware.CorsMiddleware",
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
#
# ROOT_URLCONF = 'LearnScroll.urls'
#
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = 'LearnScroll.wsgi.application'
# ASGI_APPLICATION = 'LearnScroll.asgi.application'
#
# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#         'OPTIONS': {
#             'timeout': 60,
#         },
#     }
# }
#
# from django.db.backends.signals import connection_created
#
#
# def _activate_sqlite_wal(sender, connection, **kwargs):
#     if connection.vendor == 'sqlite':
#         cursor = connection.cursor()
#         cursor.execute('PRAGMA journal_mode=WAL;')
#         cursor.execute('PRAGMA synchronous=NORMAL;')
#         cursor.execute('PRAGMA busy_timeout=30000;')  # ms
#
#
# connection_created.connect(_activate_sqlite_wal)
# url = urlparse(os.getenv("DATABASE_URL"))
# #
# # DATABASES = {
# #     "default": {
# #         "ENGINE": "django.db.backends.postgresql",
# #         "NAME": url.path[1:],
# #         "USER": url.username,
# #         "PASSWORD": url.password,
# #         "HOST": url.hostname,
# #         "PORT": url.port,
# #     }
# # }
#
# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
#
#
#
#
#
#
#
#
#
#
# #
# # CHANNEL_LAYERS = {
# #     "default": {
# #         "BACKEND": "channels_redis.core.RedisChannelLayer",
# #         "CONFIG": {
# #             "hosts": [("127.0.0.1", 6379)],
# #         },
# #     },
# # }
#
#
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     },
# }
#
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
#
#
# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/
#
# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'Asia/Kolkata'
#
# USE_I18N = True
#
# USE_TZ = True
#
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/
#
# STATIC_URL = 'static/'
#
#
# from datetime import timedelta
#
# REST_FRAMEWORK = {
#     "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
#
#     "DEFAULT_AUTHENTICATION_CLASSES": (
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#     ),
# }
# # REST_FRAMEWORK = {
# #     'DEFAULT_AUTHENTICATION_CLASSES': [
# #         'rest_framework.authentication.TokenAuthentication',
# #         'rest_framework.authentication.SessionAuthentication',
# #     ],
# #     'DEFAULT_PERMISSION_CLASSES': [
# #         'rest_framework.permissions.IsAuthenticatedOrReadOnly',
# #     ],
# #     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
# #     'PAGE_SIZE': 20
# # }
#
# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
#
#     "ROTATE_REFRESH_TOKENS": False,
#     "BLACKLIST_AFTER_ROTATION": True,
#
#     "ALGORITHM": "HS256",
#
#     "SIGNING_KEY": SECRET_KEY,
#
#     "AUTH_HEADER_TYPES": ("Bearer",),
# }
# AUTH_USER_MODEL = "login.User"
# # AUTH_USER_MODEL = "authentication.User"
# CORS_ALLOW_ALL_ORIGINS = True
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'
# os.makedirs(MEDIA_ROOT, exist_ok=True)
#
# SPECTACULAR_SETTINGS = {
#     'TITLE': 'LearnScroll API',
#     'DESCRIPTION': 'LearnScroll Production API',
#     'VERSION': '1.0.0',
#     'SERVE_INCLUDE_SCHEMA': False,
#     'COMPONENT_SPLIT_REQUEST': True,
# }
#
# #
# GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
#
# DATA_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024
# FILE_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024
# FILE_UPLOAD_PERMISSIONS = 0o644
#
# # Timeout badhao
# DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
# # settings.py ke last me add karein
# FCM_SERVICE_ACCOUNT_JSON_PATH = BASE_DIR / "firebase-service-account.json"











"""
Django settings for LearnScroll project.
PRODUCTION READY - AI Study Room included
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from django.db.backends.signals import connection_created

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# SECURITY
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "True") == "True"  # .env me DEBUG=False kar dena production pe
ALLOWED_HOSTS = ['*', '10.93.221.189', 'localhost', '127.0.0.1']

# Application definition
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    "rest_framework",
    "drf_spectacular",
    'corsheaders',
    'login',
    'user_profile',
    'post',
    "message",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LearnScroll.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LearnScroll.wsgi.application'
ASGI_APPLICATION = 'LearnScroll.asgi.application'

# Database - SQLite WAL mode
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 60,
        },
    }
}

def _activate_sqlite_wal(sender, connection, **kwargs):
    if connection.vendor == 'sqlite':
        cursor = connection.cursor()
        cursor.execute('PRAGMA journal_mode=WAL;')
        cursor.execute('PRAGMA synchronous=NORMAL;')
        cursor.execute('PRAGMA busy_timeout=30000;')

connection_created.connect(_activate_sqlite_wal)

# For Postgres later - abhi comment me rehne de
# from urllib.parse import urlparse
# url = urlparse(os.getenv("DATABASE_URL"))
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": url.path[1:],
#         "USER": url.username,
#         "PASSWORD": url.password,
#         "HOST": url.hostname,
#         "PORT": url.port,
#     }
# }

# Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}
# Production pe Redis lagayega to ye use karna:
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
#     },
# }

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
os.makedirs(MEDIA_ROOT, exist_ok=True)

# --- PRODUCTION AI FIX ---
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "learnscroll-ai-cache",
    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "100/min",
        "ai_study": "20/min",
    }
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

AUTH_USER_MODEL = "login.User"
CORS_ALLOW_ALL_ORIGINS = True

SPECTACULAR_SETTINGS = {
    'TITLE': 'LearnScroll API',
    'DESCRIPTION': 'LearnScroll Production API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

# Upload limits
DATA_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024
FILE_UPLOAD_PERMISSIONS = 0o644
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

FCM_SERVICE_ACCOUNT_JSON_PATH = BASE_DIR / "firebase-service-account.json"
