# Generated by Django 5.2.17 on 2026-09-28 15:27

import common.attachment_validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='assigments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('personal', 'Personal'), ('campus', 'Campus'), ('tuitionclass', 'TuitionClass')], db_index=True, max_length=20)),
                ('context_type', models.CharField(blank=True, max_length=20)),
                ('context_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assigments/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('has_structured_questions', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('kind', models.CharField(choices=[('assignment', 'Assignment'), ('project', 'Project')], default='assignment', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', max_length=10)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('link', 'Anyone with the link'), ('public', 'Public')], db_index=True, default='private', max_length=7)),
                ('public_slug', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=6)),
                ('submission_types', models.JSONField(blank=True, default=list)),
                ('rubric', models.JSONField(blank=True, default=list)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_assigmentss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='assigmentsQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('text', 'Text / Subjective'), ('mcq', 'Multiple Choice (single answer)'), ('msq', 'Multiple Select (multiple answers)'), ('list', 'List / Ordered Items')], db_index=True, max_length=4)),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assigments/question_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('marks', models.PositiveIntegerField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(blank=True, default=dict)),
                ('assigments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assigments.assigments')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='assigmentsSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('written_content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='assigments/submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('roll_number', models.CharField(blank=True, max_length=30)),
                ('enrollment_no', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('submitted', 'Submitted'), ('late', 'Late'), ('partially_checked', 'Partially Checked'), ('checked', 'Checked')], db_index=True, default='missing', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('link_url', models.URLField(blank=True, max_length=500)),
                ('rubric_scores', models.JSONField(blank=True, default=dict)),
                ('total_marks_awarded', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('public_slug', models.CharField(blank=True, max_length=40)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('assigments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assigments.assigments')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigments_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='assigmentsAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_data', models.JSONField(default=dict)),
                ('answer_attachment', models.FileField(blank=True, null=True, upload_to='assigments/answer_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('is_auto_graded', models.BooleanField()),
                ('is_correct', models.BooleanField(null=True)),
                ('marks_awarded', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewer_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assigments_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assigments.assigmentsquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assigments.assigmentssubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionSimilarityFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('similarity_score', models.FloatField()),
                ('excerpt_a', models.TextField(blank=True)),
                ('excerpt_b', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('confirmed', 'Confirmed duplicate'), ('dismissed', 'Dismissed (false positive)')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assigments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_flags', to='assigments.assigments')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similarity_flags', to='assigments.assigmentsquestion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_similarity_flags', to=settings.AUTH_USER_MODEL)),
                ('submission_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_flags_as_a', to='assigments.assigmentssubmission')),
                ('submission_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_flags_as_b', to='assigments.assigmentssubmission')),
            ],
        ),
        migrations.AddIndex(
            model_name='assigments',
            index=models.Index(fields=['source', 'context_type', 'context_id'], name='assigments__source_6545fc_idx'),
        ),
        migrations.AddIndex(
            model_name='assigments',
            index=models.Index(fields=['posted_by', 'due_date'], name='assigments__posted__f16dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='assigments',
            index=models.Index(fields=['status', 'visibility', '-published_at'], name='assign_explore_idx'),
        ),
        migrations.AddConstraint(
            model_name='assigmentsquestion',
            constraint=models.UniqueConstraint(fields=('assigments', 'order'), name='unique_question_order_per_assigments'),
        ),
        migrations.AddIndex(
            model_name='assigmentssubmission',
            index=models.Index(fields=['assigments', 'status'], name='assigments__assigme_33be3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='assigmentssubmission',
            constraint=models.UniqueConstraint(fields=('assigments', 'student'), name='unique_submission_per_student'),
        ),
        migrations.AddConstraint(
            model_name='assigmentssubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('public_slug', ''), _negated=True), fields=('public_slug',), name='unique_nonblank_public_slug'),
        ),
        migrations.AddConstraint(
            model_name='assigmentsanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_answer_per_submission_question'),
        ),
        migrations.AddIndex(
            model_name='submissionsimilarityflag',
            index=models.Index(fields=['assigments', 'status'], name='assigments__assigme_58a2f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionsimilarityflag',
            constraint=models.UniqueConstraint(fields=('assigments', 'submission_a', 'submission_b', 'question'), name='unique_similarity_flag_per_pair_question'),
        ),
    ]
