# Generated by Django 6.0.6 on 2026-09-09 13:25

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liveclass', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='pinned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='liveclass.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessageread',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='liveclass.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessageread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessagereport',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='liveclass.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessagereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessagereport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatreaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='liveclass.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classholiday',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classjoinrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classjoinrequest',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classjoinrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classmaterial',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classjoinrequest',
            name='class_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='liveclass.classpass'),
        ),
        migrations.AddField(
            model_name='classquery',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries_answered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classquery',
            name='asked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries_asked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_teaching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classquery',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classpass',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classmaterial',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classjoinrequest',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classholiday',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classroomban',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_bans_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomban',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classroomban',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_reports_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomreview',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classroomreview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomshare',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classroomshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_shares_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomshare',
            name='shared_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_shares_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomstaff',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classroomstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomwishlist',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classroomwishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classholiday',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Leave blank to mark this date off across every schedule in the classroom.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='liveclass.classschedule'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='liveclass.classschedule'),
        ),
        migrations.AddField(
            model_name='classreminder',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='classquery',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional — set if the doubt is about a specific live session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='classmaterial',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='breakoutroom',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_rooms', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='coinpurchase',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='liveclass.coinpurchase'),
        ),
        migrations.AddField(
            model_name='coinpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coinwithdrawal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_withdrawals_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coinwithdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livepoll',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livepoll',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='notice',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='notice',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentteachermessage',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='parentteachermessage',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_messages_replied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentteachermessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentteachermessage',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Set only when the chosen template has requires_session=True.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_messages', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='parentteachermessage',
            name='template',
            field=models.ForeignKey(help_text='PROTECT, not CASCADE/SET_NULL: a template must never be hard-deleted while any sent message still references it — retire it via is_active instead.', on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='liveclass.parentmessagetemplate'),
        ),
        migrations.AddField(
            model_name='passdailycharge',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_charges', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='passgift',
            name='class_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='liveclass.classpass'),
        ),
        migrations.AddField(
            model_name='passgift',
            name='gifter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_gifted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passgift',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_gifted_to_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='class_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='liveclass.classpass'),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='liveclass.coupon'),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='renewed_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_into', to='liveclass.passpurchase'),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passgift',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_gift', to='liveclass.passpurchase'),
        ),
        migrations.AddField(
            model_name='passdailycharge',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_charges', to='liveclass.passpurchase'),
        ),
        migrations.AddField(
            model_name='classjoinrequest',
            name='pass_purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_request', to='liveclass.passpurchase'),
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='liveclass.livepoll'),
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polltemplate',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_templates', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='polltemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_poll_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_used', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessioncaption',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_log', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='sessioncaption',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_captions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='breakout_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='liveclass.breakoutroom'),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionreaction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_log', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='sessionreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionreadstate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='sessionreadstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_read_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionwaitlist',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='sessionwaitlist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlisted_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentreportcard',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='studentreportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='chatmessageread',
            index=models.Index(fields=['message'], name='liveclass_c_message_dfac40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessageread',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatmessagereport',
            index=models.Index(fields=['status', '-created_at'], name='liveclass_c_status_6ea1c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessagereport',
            unique_together={('message', 'reporter')},
        ),
        migrations.AddIndex(
            model_name='chatreaction',
            index=models.Index(fields=['message'], name='liveclass_c_message_4de2d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatreaction',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='chunkedupload',
            index=models.Index(fields=['status', 'created_at'], name='liveclass_c_status_1837c4_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkedupload',
            index=models.Index(fields=['user', 'status'], name='liveclass_c_user_id_d4fdc4_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['teacher', 'is_active'], name='liveclass_c_teacher_d87f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['-rating_avg'], name='liveclass_c_rating__85fd29_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['language'], name='liveclass_c_languag_263e46_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['classroom_type'], name='liveclass_c_classro_3a5aec_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_deleted'], name='liveclass_c_is_dele_fb7c32_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='classroom_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=django.contrib.postgres.indexes.GinIndex(fields=['subject'], name='classroom_subject_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='classroom_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('classroom', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='classroomban',
            unique_together={('classroom', 'student')},
        ),
        migrations.AddIndex(
            model_name='classroomreport',
            index=models.Index(fields=['classroom', 'status'], name='liveclass_c_classro_1daebb_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('classroom', 'reported_by'), name='one_pending_report_per_user_per_classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomreview',
            unique_together={('classroom', 'student')},
        ),
        migrations.AddIndex(
            model_name='classroomshare',
            index=models.Index(fields=['classroom', '-created_at'], name='liveclass_c_classro_c0b9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomshare',
            index=models.Index(fields=['shared_by', '-created_at'], name='liveclass_c_shared__b4349e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomstaff',
            unique_together={('classroom', 'user')},
        ),
        migrations.AddIndex(
            model_name='classroomwishlist',
            index=models.Index(fields=['user', '-created_at'], name='liveclass_c_user_id_a9c030_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomwishlist',
            unique_together={('user', 'classroom')},
        ),
        migrations.AddIndex(
            model_name='classholiday',
            index=models.Index(fields=['classroom', 'date'], name='liveclass_c_classro_bf89f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classholiday',
            unique_together={('classroom', 'schedule', 'date')},
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['classroom', 'status', 'scheduled_start'], name='liveclass_c_classro_e3bf3e_idx'),
        ),
        migrations.AddIndex(
            model_name='classreminder',
            index=models.Index(fields=['remind_at', 'is_sent'], name='liveclass_c_remind__c715e7_idx'),
        ),
        migrations.AddIndex(
            model_name='classquery',
            index=models.Index(fields=['classroom', 'status', '-created_at'], name='liveclass_c_classro_ccd3df_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'sent_at'], name='liveclass_c_session_6bacc8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_flagged'], name='liveclass_c_is_flag_8a3de0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breakoutroom',
            unique_together={('session', 'room_number')},
        ),
        migrations.AddIndex(
            model_name='coinpurchase',
            index=models.Index(fields=['user', 'status', '-created_at'], name='liveclass_c_user_id_4cc80e_idx'),
        ),
        migrations.AddIndex(
            model_name='coinwithdrawal',
            index=models.Index(fields=['status', 'requested_at'], name='liveclass_c_status_aa17a4_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['classroom', 'is_pinned', '-created_at'], name='liveclass_n_classro_077da8_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['classroom', 'expires_at'], name='liveclass_n_classro_734c46_idx'),
        ),
        migrations.AddIndex(
            model_name='parentteachermessage',
            index=models.Index(fields=['classroom', 'status', '-created_at'], name='liveclass_p_classro_7ba6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='parentteachermessage',
            index=models.Index(fields=['sender', '-created_at'], name='liveclass_p_sender__18a89e_idx'),
        ),
        migrations.AddIndex(
            model_name='passpurchase',
            index=models.Index(fields=['student', 'status', 'expires_at'], name='liveclass_p_student_554c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='passpurchase',
            index=models.Index(fields=['referred_by'], name='liveclass_p_referre_760a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='passpurchase',
            index=models.Index(fields=['auto_renew', 'status', 'expires_at'], name='liveclass_p_auto_re_32c56d_idx'),
        ),
        migrations.AddIndex(
            model_name='passgift',
            index=models.Index(fields=['recipient', 'status'], name='liveclass_p_recipie_624a23_idx'),
        ),
        migrations.AddIndex(
            model_name='passgift',
            index=models.Index(fields=['status', 'expires_at'], name='liveclass_p_status_9c5de4_idx'),
        ),
        migrations.AddConstraint(
            model_name='passdailycharge',
            constraint=models.UniqueConstraint(fields=('purchase', 'date'), name='one_charge_per_purchase_per_day'),
        ),
        migrations.AddIndex(
            model_name='classjoinrequest',
            index=models.Index(fields=['classroom', 'status'], name='liveclass_c_classro_a400e6_idx'),
        ),
        migrations.AddIndex(
            model_name='classjoinrequest',
            index=models.Index(fields=['student', 'status'], name='liveclass_c_student_1998fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='classjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('classroom', 'student'), name='one_pending_join_request_per_student_per_classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='pollresponse',
            unique_together={('poll', 'student')},
        ),
        migrations.AddIndex(
            model_name='sessioncaption',
            index=models.Index(fields=['session', 'created_at'], name='liveclass_s_session_fa6283_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'user', 'joined_at')},
        ),
        migrations.AddIndex(
            model_name='sessionreaction',
            index=models.Index(fields=['session', 'created_at'], name='liveclass_s_session_41b546_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionreadstate',
            unique_together={('session', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionwaitlist',
            unique_together={('session', 'student')},
        ),
        migrations.AddIndex(
            model_name='studentreportcard',
            index=models.Index(fields=['classroom', 'student'], name='liveclass_s_classro_f3deff_idx'),
        ),
    ]
