# Generated by Django 6.0.6 on 2026-08-11 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in coins (User.coin). 0 = free pass.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_teaching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passpurchase',
            name='payment_method',
            field=models.CharField(choices=[('coin_wallet', 'Coin Wallet'), ('free', 'Free')], default='coin_wallet', max_length=20),
        ),
    ]
