# Generated by Django 6.0.6 on 2026-08-11 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0002_alter_classpass_price_alter_classroom_teacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, help_text="e.g. 'Diwali', 'Teacher on leave'", max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ClassQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered')], default='open', max_length=10)),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional auto-hide time, e.g. for a one-off exam-date notice.', null=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='enrolled_count',
            field=models.PositiveIntegerField(default=0, help_text='Distinct students currently holding an active, unexpired pass.'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='classroom',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='classroom',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['-rating_avg'], name='liveclass_c_rating__85fd29_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['language'], name='liveclass_c_languag_263e46_idx'),
        ),
        migrations.AddField(
            model_name='classholiday',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classholiday',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classholiday',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Leave blank to mark this date off across every schedule in the classroom.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='liveclass.classschedule'),
        ),
        migrations.AddField(
            model_name='classquery',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries_answered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classquery',
            name='asked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries_asked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classquery',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classquery',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional — set if the doubt is about a specific live session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='notice',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='notice',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='classholiday',
            index=models.Index(fields=['classroom', 'date'], name='liveclass_c_classro_bf89f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classholiday',
            unique_together={('classroom', 'schedule', 'date')},
        ),
        migrations.AddIndex(
            model_name='classquery',
            index=models.Index(fields=['classroom', 'status', '-created_at'], name='liveclass_c_classro_ccd3df_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['classroom', 'is_pinned', '-created_at'], name='liveclass_n_classro_077da8_idx'),
        ),
    ]
