# Generated by Django 6.0.6 on 2026-08-15 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0003_classholiday_classquery_notice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classroom_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organisation', 'Organisation')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='classroom',
            name='organisation_name',
            field=models.CharField(blank=True, help_text="Required when classroom_type is 'organisation'.", max_length=150),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['classroom_type'], name='liveclass_c_classro_3a5aec_idx'),
        ),
    ]
