# Generated by Django 6.0.6 on 2026-08-21 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0004_classroom_classroom_type_classroom_organisation_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('message', models.CharField(blank=True, help_text='Optional note from the student to the teacher.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('class_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='liveclass.classpass')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='liveclass.classroom')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('pass_purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_request', to='liveclass.passpurchase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['classroom', 'status'], name='liveclass_c_classro_a400e6_idx'), models.Index(fields=['student', 'status'], name='liveclass_c_student_1998fe_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('classroom', 'student'), name='one_pending_join_request_per_student_per_classroom')],
            },
        ),
    ]
