# Generated by Django 6.0.6 on 2026-08-22 15:35

import django.core.validators
import liveclass.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0005_classjoinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', validators=[liveclass.models.MaxFileSizeValidator(50)]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(upload_to='assignment_submissions/', validators=[liveclass.models.MaxFileSizeValidator(50)]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[liveclass.models.MaxFileSizeValidator(10)]),
        ),
        migrations.AlterField(
            model_name='classmaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='class_materials/', validators=[liveclass.models.MaxFileSizeValidator(100)]),
        ),
        migrations.AlterField(
            model_name='classpass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in coins (User.coin). 0 = free pass.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='classpass',
            name='validity_days',
            field=models.PositiveIntegerField(help_text='How many days this pass stays valid after purchase', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='classroom_covers/', validators=[liveclass.models.MaxFileSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='max_participants',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
