# Generated by Django 6.0.6 on 2026-08-23 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0006_alter_assignment_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', 'Scam / took coins, no class'), ('not_delivering', 'Classes not happening as promised'), ('inappropriate', 'Inappropriate content or behaviour'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_deleted'], name='liveclass_c_is_dele_fb7c32_idx'),
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_reports_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='classroomreport',
            index=models.Index(fields=['classroom', 'status'], name='liveclass_c_classro_1daebb_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('classroom', 'reported_by'), name='one_pending_report_per_user_per_classroom'),
        ),
    ]
