# Generated by Django 6.0.6 on 2026-08-27 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0008_sessionparticipant_kicked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='egress_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='hand_raised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('join_request_received', 'Join Request Received'), ('join_request_accepted', 'Join Request Accepted'), ('join_request_rejected', 'Join Request Rejected'), ('pass_refunded', 'Pass Refunded'), ('session_reminder', 'Session Reminder'), ('assignment_graded', 'Assignment Graded'), ('query_answered', 'Doubt Answered'), ('certificate_issued', 'Certificate Issued'), ('waitlist_promoted', 'Waitlist Promoted'), ('classroom_flagged', 'Classroom Flagged'), ('notice_posted', 'Notice Posted'), ('session_live', 'Class Started'), ('session_cancelled', 'Session Cancelled'), ('assignment_posted', 'New Assignment'), ('submission_received', 'New Submission'), ('staff_added', 'Added As Staff'), ('review_posted', 'New Review'), ('report_reviewed', 'Report Reviewed'), ('generic', 'Generic')], default='generic', max_length=30),
        ),
        migrations.CreateModel(
            name='BreakoutRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_rooms', to='liveclass.classsession')),
            ],
            options={
                'ordering': ['room_number'],
                'unique_together': {('session', 'room_number')},
            },
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='breakout_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='liveclass.breakoutroom'),
        ),
    ]
