# Generated by Django 6.0.6 on 2026-08-27 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0009_classsession_egress_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passpurchase',
            name='coins_released',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='last_charge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='per_day_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='reason',
            field=models.CharField(choices=[('pass_purchase', 'Pass Purchase'), ('class_earning', 'Class Earning'), ('referral_bonus', 'Referral Bonus'), ('refund', 'Refund'), ('admin_adjustment', 'Admin Adjustment'), ('topup', 'Wallet Top-up')], max_length=20),
        ),
        migrations.CreateModel(
            name='PassDailyCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_charges', to='liveclass.passpurchase')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_charges', to='liveclass.classsession')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('purchase', 'date'), name='one_charge_per_purchase_per_day')],
            },
        ),
    ]
