# Generated by Django 6.0.6 on 2026-08-31 10:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0013_classroom_share_count_alter_cointransaction_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('thumbs_up', '👍'), ('heart', '❤️'), ('laugh', '😂')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField()),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('gateway_signature', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_chat_message_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_seen_poll_id', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='pinned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classjoinrequest',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='referral_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="% of each day's released class-earning charge (see PassPurchase.charge_for_session) that also gets paid to whoever referred the student, on top of the teacher's own share — not deducted from it. Only takes effect while referral_enabled=True.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='classroom',
            name='referral_enabled',
            field=models.BooleanField(default=False, help_text='When on, any authenticated user can generate a shareable referral link for this classroom (see classrooms/{id}/refer-link/) and earn a daily commission on any pass purchase that comes in through it.'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='caption_status',
            field=models.CharField(choices=[('none', 'Not Requested'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='classsession',
            name='caption_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='passdailycharge',
            name='referral_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='referral_coins_released',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='referral_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='referral_per_day_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='refunded_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classreminder',
            name='channel',
            field=models.CharField(choices=[('push', 'Push Notification'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='push', max_length=10),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='reason',
            field=models.CharField(choices=[('pass_purchase', 'Pass Purchase'), ('class_earning', 'Class Earning'), ('referral_bonus', 'Referral Bonus'), ('class_referral_commission', 'Class Referral Commission'), ('refund', 'Refund'), ('admin_adjustment', 'Admin Adjustment'), ('topup', 'Wallet Top-up'), ('withdrawal', 'Withdrawal'), ('withdrawal_reversed', 'Withdrawal Reversed')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='passpurchase',
            index=models.Index(fields=['referred_by'], name='liveclass_p_referre_760a0e_idx'),
        ),
        migrations.AddField(
            model_name='chatreaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='liveclass.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coinpurchase',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='liveclass.coinpurchase'),
        ),
        migrations.AddField(
            model_name='coinpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polltemplate',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_templates', to='liveclass.classroom'),
        ),
        migrations.AddField(
            model_name='polltemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_poll_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionreadstate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='liveclass.classsession'),
        ),
        migrations.AddField(
            model_name='sessionreadstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_read_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatreaction',
            index=models.Index(fields=['message'], name='liveclass_c_message_4de2d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatreaction',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='coinpurchase',
            index=models.Index(fields=['user', 'status', '-created_at'], name='liveclass_c_user_id_4cc80e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionreadstate',
            unique_together={('session', 'user')},
        ),
    ]
