# Generated by Django 6.0.6 on 2026-08-31 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0014_chatreaction_coinpurchase_polltemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('abusive', 'Abusive / Harassment'), ('spam', 'Spam / Advertising'), ('off_topic', 'Off-topic'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('muted_types', models.JSONField(blank=True, default=list, help_text='List of Notification.NotifType values.')),
                ('digest_frequency', models.CharField(choices=[('off', 'Off'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='off', max_length=10)),
                ('last_digest_sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_spent', models.PositiveIntegerField(help_text="Frozen at gift time — the class_pass's price then.")),
                ('gift_message', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Claim'), ('claimed', 'Claimed'), ('cancelled', 'Cancelled By Gifter'), ('expired', 'Expired Unclaimed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='flagged_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classsession',
            name='engagement_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='renewal_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passpurchase',
            name='renewed_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_into', to='liveclass.passpurchase'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='reason',
            field=models.CharField(choices=[('pass_purchase', 'Pass Purchase'), ('class_earning', 'Class Earning'), ('referral_bonus', 'Referral Bonus'), ('class_referral_commission', 'Class Referral Commission'), ('refund', 'Refund'), ('gift_sent', 'Pass Gifted To Someone'), ('gift_cancelled_refund', 'Unclaimed Gift Refunded'), ('pass_auto_renewed', 'Pass Auto-Renewed'), ('admin_adjustment', 'Admin Adjustment'), ('topup', 'Wallet Top-up'), ('withdrawal', 'Withdrawal'), ('withdrawal_reversed', 'Withdrawal Reversed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('join_request_received', 'Join Request Received'), ('join_request_accepted', 'Join Request Accepted'), ('join_request_rejected', 'Join Request Rejected'), ('pass_refunded', 'Pass Refunded'), ('session_reminder', 'Session Reminder'), ('assignment_graded', 'Assignment Graded'), ('query_answered', 'Doubt Answered'), ('certificate_issued', 'Certificate Issued'), ('waitlist_promoted', 'Waitlist Promoted'), ('classroom_flagged', 'Classroom Flagged'), ('notice_posted', 'Notice Posted'), ('session_live', 'Class Started'), ('session_cancelled', 'Session Cancelled'), ('assignment_posted', 'New Assignment'), ('submission_received', 'New Submission'), ('staff_added', 'Added As Staff'), ('review_posted', 'New Review'), ('report_reviewed', 'Report Reviewed'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('withdrawal_paid', 'Withdrawal Paid'), ('classroom_shared', 'Classroom Shared With You'), ('pass_gift_received', 'Pass Gift Received'), ('pass_gift_claimed', 'Pass Gift Claimed'), ('pass_auto_renewed', 'Pass Auto-Renewed'), ('auto_renew_failed', 'Auto-Renewal Failed'), ('pass_gift_expired', 'Gift Expired & Refunded'), ('generic', 'Generic')], default='generic', max_length=30),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_flagged'], name='liveclass_c_is_flag_8a3de0_idx'),
        ),
        migrations.AddIndex(
            model_name='passpurchase',
            index=models.Index(fields=['auto_renew', 'status', 'expires_at'], name='liveclass_p_auto_re_32c56d_idx'),
        ),
        migrations.AddField(
            model_name='chatmessagereport',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='liveclass.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessagereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessagereport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passgift',
            name='class_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='liveclass.classpass'),
        ),
        migrations.AddField(
            model_name='passgift',
            name='gifter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_gifted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passgift',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_gift', to='liveclass.passpurchase'),
        ),
        migrations.AddField(
            model_name='passgift',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_gifted_to_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatmessagereport',
            index=models.Index(fields=['status', '-created_at'], name='liveclass_c_status_6ea1c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessagereport',
            unique_together={('message', 'reporter')},
        ),
        migrations.AddIndex(
            model_name='passgift',
            index=models.Index(fields=['recipient', 'status'], name='liveclass_p_recipie_624a23_idx'),
        ),
        migrations.AddIndex(
            model_name='passgift',
            index=models.Index(fields=['status', 'expires_at'], name='liveclass_p_status_9c5de4_idx'),
        ),
    ]
