# Generated by Django 6.0.6 on 2026-09-02 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0016_breakoutroom_sessionparticipant_breakout_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='captions_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classsession',
            name='transcription_job_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='breakoutroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='referral_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="% of each day's released class-earning charge (see PassPurchase.charge_for_session) that gets paid to whoever referred the student — deducted OUT OF the teacher's own share, never added on top by the platform. The teacher sets this rate themselves and funds it out of their own earnings. Only takes effect while referral_enabled=True.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
