# Generated by Django 6.0.6 on 2026-09-06 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0018_chatmessage_reply_to_classpass_allow_gifting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['classroom', 'expires_at'], name='liveclass_n_classro_734c46_idx'),
        ),
    ]
