# Generated by Django 6.0.6 on 2026-09-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('join_request_received', 'Join Request Received'), ('join_request_accepted', 'Join Request Accepted'), ('join_request_rejected', 'Join Request Rejected'), ('pass_refunded', 'Pass Refunded'), ('session_reminder', 'Session Reminder'), ('assigments_graded', 'assigments Graded'), ('query_answered', 'Doubt Answered'), ('certificate_issued', 'Certificate Issued'), ('waitlist_promoted', 'Waitlist Promoted'), ('classroom_flagged', 'Classroom Flagged'), ('notice_posted', 'Notice Posted'), ('session_live', 'Class Started'), ('session_cancelled', 'Session Cancelled'), ('assigments_posted', 'New assigments'), ('submission_received', 'New Submission'), ('staff_added', 'Added As Staff'), ('review_posted', 'New Review'), ('report_reviewed', 'Report Reviewed'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('withdrawal_paid', 'Withdrawal Paid'), ('classroom_shared', 'Classroom Shared With You'), ('pass_gift_received', 'Pass Gift Received'), ('pass_gift_claimed', 'Pass Gift Claimed'), ('pass_auto_renewed', 'Pass Auto-Renewed'), ('auto_renew_failed', 'Auto-Renewal Failed'), ('pass_gift_expired', 'Gift Expired & Refunded'), ('generic', 'Generic'), ('chat_message', 'New Message'), ('mention', 'You Were Mentioned'), ('incoming_call', 'Incoming Call'), ('parent_device_pending', 'Parent Device Pending Approval'), ('post_liked', 'Post Liked'), ('post_commented', 'Post Commented'), ('campus_session_scheduled', 'Campus Session Scheduled'), ('campus_session_live', 'Campus Session Live'), ('low_attendance_alert', 'Low Attendance Alert'), ('assigments_posted_campus', 'New Campus assigments'), ('assigments_due_reminder', 'assigments Due Reminder'), ('result_published', 'Result Published'), ('fee_due_reminder', 'Fee Due Reminder'), ('staff_assigments_approved', 'Staff assigments Approved'), ('staff_assigments_rejected', 'Staff assigments Rejected'), ('testseries_posted', 'New Test Series'), ('testseries_checked', 'Test Series Checked'), ('testseries_payout_released', 'Test Series Payout Released'), ('assigments_due_soon', 'assigments Due Soon'), ('campus_reward_earned', 'Campus Reward Earned'), ('testseries_review_received', 'New Test Series Review'), ('testseries_query_received', 'New Test Series Query'), ('testseries_query_answered', 'Test Series Query Answered'), ('follow_request_received', 'Follow Request Received'), ('follow_request_accepted', 'Follow Request Accepted'), ('new_post_from_followed', 'New Post From Someone You Follow'), ('classroom_created_by_followed', 'New Classroom From Someone You Follow'), ('testseries_created_by_followed', 'New Test Series From Someone You Follow')], db_index=True, default='generic', max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'liveclass_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('muted_types', models.JSONField(blank=True, default=list, help_text='List of Notification.NotifType values.')),
                ('digest_frequency', models.CharField(choices=[('off', 'Off'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='off', max_length=10)),
                ('last_digest_sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'liveclass_notificationpreference',
            },
        ),
    ]
