# Generated by Django 6.0.6 on 2026-09-09 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('liveclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='liveclass.classroom'),
        ),
    ]
