# Generated by Django 6.0.6 on 2026-10-06 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_story_reaction_post_reposted_notif_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='dnd_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.CreateModel(
            name='NotificationMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muted_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by_notification_mutes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_notification_mute',
                'constraints': [models.UniqueConstraint(fields=('user', 'muted_actor'), name='uniq_notification_mute_pair'), models.CheckConstraint(condition=models.Q(('user', models.F('muted_actor')), _negated=True), name='notification_mute_not_self')],
            },
        ),
    ]
