# Generated by Django 6.0.6 on 2026-09-18 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostChunkedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(max_length=100, unique=True)),
                ('file_name', models.CharField(max_length=500)),
                ('total_chunks', models.IntegerField()),
                ('total_size', models.BigIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('content', models.TextField(blank=True, default='')),
                ('category', models.CharField(default='general', max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('post_type', models.CharField(default='video', max_length=20)),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('media_caption', models.CharField(blank=True, default='', max_length=500)),
                ('media_type', models.CharField(blank=True, default='', max_length=20)),
                ('poll_options', models.JSONField(blank=True, default=list)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('total_votes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_polls',
            },
        ),
        migrations.CreateModel(
            name='PostPollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('votes_count', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'post_poll_options',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PostPollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_poll_votes',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='is_scheduled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'subcategory', '-created_at'], name='posts_categor_08a0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_scheduled', 'published_at'], name='posts_is_sche_be50e0_idx'),
        ),
        migrations.AddField(
            model_name='postchunkedupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postpoll',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='post.post'),
        ),
        migrations.AddField(
            model_name='postpolloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='post.postpoll'),
        ),
        migrations.AddField(
            model_name='postpollvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='post.postpolloption'),
        ),
        migrations.AddField(
            model_name='postpollvote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='post.postpoll'),
        ),
        migrations.AddField(
            model_name='postpollvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_poll_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='postpolloption',
            index=models.Index(fields=['poll', 'display_order'], name='post_poll_o_poll_id_469995_idx'),
        ),
        migrations.AddIndex(
            model_name='postpollvote',
            index=models.Index(fields=['option'], name='post_poll_v_option__674589_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postpollvote',
            unique_together={('poll', 'user')},
        ),
    ]
