# Generated by Django 6.0.6 on 2026-07-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='confuse_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='explain_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='imp_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='wrong_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'like'), ('confuse', 'confuse'), ('wrong', 'wrong'), ('imp', 'imp'), ('explain', 'explain')], default='like', max_length=20),
        ),
    ]
