# Generated by Django 6.0.6 on 2026-08-07 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_commentlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('early_childhood', 'Early Childhood (Pre-Nursery–UKG)'), ('primary', 'Primary (Class 1–5)'), ('middle_school', 'Middle School (Class 6–8)'), ('secondary', 'Secondary (Class 9–10)'), ('senior_secondary', 'Senior Secondary (Class 11–12)'), ('engineering', 'Engineering'), ('medical_health', 'Medical & Health Sciences'), ('commerce_management', 'Commerce & Management'), ('arts_humanities_courses', 'Arts & Humanities (Courses)'), ('law', 'Law'), ('design_architecture', 'Design & Architecture'), ('agriculture', 'Agriculture & Allied Sciences'), ('aviation_hospitality_media', 'Aviation, Hospitality & Mass Media'), ('other_professional_courses', 'Other Professional Courses'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('mathematics', 'Mathematics'), ('computer_science', 'Computer Science & IT'), ('languages', 'Languages'), ('social_sciences', 'Social Sciences'), ('philosophy_spirituality', 'Philosophy & Spirituality'), ('technical_skills', 'Technical Skills'), ('soft_skills', 'Soft Skills'), ('creative_skills', 'Creative Skills'), ('life_financial_skills', 'Life & Financial Skills'), ('career_vocational_skills', 'Career & Vocational Skills'), ('science_experiments', 'Science Experiments'), ('stem_robotics', 'STEM & Robotics Projects'), ('diy_projects', 'DIY & Maker Projects'), ('coding_projects', 'Coding Projects & Mini Apps'), ('authors', 'Famous Authors'), ('stories', 'Stories'), ('novels', 'Novels'), ('poetry', 'Poetry'), ('drama', 'Drama & Playwriting'), ('literary_genres', 'Literary Genres'), ('scientists_inventors', 'Scientists & Inventors'), ('leaders_freedom_fighters', 'Leaders & Freedom Fighters'), ('entrepreneurs', 'Entrepreneurs & Business Icons'), ('sportspersons', 'Sportspersons & Athletes'), ('artists_musicians', 'Artists, Musicians & Performers'), ('spiritual_thinkers', 'Spiritual & Philosophical Thinkers'), ('success_stories', 'Success Stories & Case Studies'), ('quotes_life_lessons', 'Quotes, Thoughts & Life Lessons'), ('school_level_exams', 'School-Level (Olympiads, NTSE)'), ('engg_medical_entrance', 'Engineering & Medical Entrance (JEE/NEET)'), ('govt_jobs', 'Government Jobs (UPSC/SSC/Banking/Railways)'), ('study_abroad', 'Study Abroad (GRE/GMAT/IELTS/TOEFL/SAT)'), ('defense_exams', 'Defense Exams (NDA/CDS)'), ('daily_current_affairs', 'Daily Current Affairs'), ('world_history_culture', 'World History & Culture'), ('indian_polity', 'Indian Polity & Constitution'), ('science_tech_updates', 'Science & Technology Updates'), ('sports_gk', 'Sports GK'), ('static_gk', 'Static GK (Awards, Books, Days)'), ('visual_arts', 'Visual Arts'), ('performing_arts', 'Performing Arts'), ('music', 'Music'), ('cultural_heritage', 'Cultural Heritage & Festivals'), ('individual_sports', 'Individual Sports'), ('team_sports', 'Team Sports'), ('fitness_yoga', 'Fitness & Yoga'), ('sports_science', 'Sports Science & Nutrition'), ('climate_ecology', 'Climate Change & Ecology'), ('renewable_energy', 'Renewable Energy'), ('sustainable_living', 'Sustainable Living'), ('child_development', 'Child Development Tips'), ('learning_activities', 'Learning Activities for Parents'), ('study_techniques', 'Study Techniques & Exam Stress Management')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('school_education', 'School Education'), ('higher_education', 'Higher Education & Courses'), ('subjects', 'Subjects'), ('skills', 'Skill-Based Learning'), ('experiments', 'Experiments & Practical Learning'), ('literature', 'Authors, Writers & Literature'), ('motivational', 'Motivational & Inspirational'), ('competitive_exams', 'Competitive Exam Preparation'), ('general_knowledge', 'General Knowledge & Current Affairs'), ('arts_culture', 'Arts, Culture & Performing Arts'), ('sports', 'Sports & Physical Education'), ('environment', 'Environment & Sustainability'), ('parenting', 'Parenting & Early Learning Support')], db_index=True, default='school_education', max_length=50),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'subcategory', '-created_at'], name='posts_categor_08a0b0_idx'),
        ),
    ]
