# Generated by Django 6.1.1 on 2026-09-30 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_story_poll_question_responses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='music',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_highlights',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HighlightItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='post.highlight')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_items', to='post.story')),
            ],
            options={
                'db_table': 'story_highlight_items',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='highlight',
            name='cover_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='post.highlightitem'),
        ),
        migrations.AddIndex(
            model_name='highlightitem',
            index=models.Index(fields=['highlight', 'position'], name='highlight_item_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='highlightitem',
            constraint=models.UniqueConstraint(fields=('highlight', 'story'), name='unique_highlight_story'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['user', '-updated_at'], name='highlight_user_upd_idx'),
        ),
    ]
