# Generated by Django 6.0.6 on 2026-08-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_is_scheduled_post_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedupload',
            name='hashtags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='location',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='media_caption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='poll_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='post_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='post_kind',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='post_subcategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='post_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='received_chunks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='upload_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('post', 'Post')], db_index=True, default='comment', max_length=10),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='visibility',
            field=models.CharField(blank=True, default='public', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chunkedupload',
            name='post_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
