# Generated by Django 6.0.6 on 2026-08-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_chunkedupload_hashtags_chunkedupload_is_scheduled_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_categor_08a0b0_idx',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='location',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='media_caption',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='poll_options',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='post_category',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='post_kind',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='post_subcategory',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='post_title',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='received_chunks',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='upload_type',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='postmedia',
            name='caption',
        ),
        migrations.AlterField(
            model_name='chunkedupload',
            name='post_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('tech', 'Technology'), ('jobs', 'Jobs'), ('news', 'News'), ('education', 'Education'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('lifestyle', 'Lifestyle'), ('other', 'Other')], db_index=True, default='general', max_length=100),
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='post',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subcategory',
        ),
    ]
