# Generated by Django 6.1.1 on 2026-09-30 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_story_music_highlights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('dwell', 'Dwell'), ('tap', 'Tap'), ('skip', 'Skip')], max_length=12)),
                ('dwell_ms', models.PositiveIntegerField(default=0)),
                ('surface', models.CharField(choices=[('feed', 'Feed'), ('reels', 'Reels'), ('profile', 'Profile'), ('explore', 'Explore')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='post_events_created_idx'), models.Index(fields=['post', 'event_type', '-created_at'], name='post_events_post_type_idx'), models.Index(fields=['user', '-created_at'], name='post_events_user_idx')],
            },
        ),
    ]