# Generated by Django 6.1.1 on 2026-10-01 18:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='medium_720',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='posts/medium_720/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='thumb_320',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='posts/thumb_320/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('y', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_hidden', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='post.post')),
                ('tagged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tagged_user', 'is_hidden', '-created_at'], name='posttag_user_hidden_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'tagged_user'), name='uniq_posttag_post_user')],
            },
        ),
    ]
