# Generated by Django 6.1.2 on 2026-10-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_highlight_cover_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('copyright_hold', 'Copyright - on hold'), ('copyright_removed', 'Copyright - removed')], default='approved', max_length=20),
        ),
    ]
