# Generated by Django 6.0.6 on 2026-08-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='otp',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='otp_hash',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
