"""
liveclass/urls.py

Registers every ViewSet with a DRF router.

In the project's main urls.py add:
    path("liveclass/", include("liveclass.urls")),

    dashboard/                           GET               (single-call home-screen summary — see
                                                          MyDashboardView in views.py)
    my-earnings/                         GET               (teacher-only earnings summary; optional
                                                          ?classroom=<id> to scope to one classroom —
                                                          see TeacherEarningsView in views.py)
    my-progress/                         GET               (caller's own attendance/assignment/
                                                          certificate stats + attendance streak —
                                                          see StudentProgressView in views.py)

Resulting endpoints (all prefixed with /liveclass/), auto-generated by the
router — list/retrieve/create/update/delete on each, plus the custom
@action endpoints noted below:

    classrooms/                          GET, POST         (?search=, ?language=, ?mine= supported on GET)
    classrooms/{id}/                     GET, PUT, PATCH, DELETE  (DELETE only once the classroom is
                                                          30+ days old AND has no active paid pass
                                                          outstanding — see Classroom.can_be_deleted();
                                                          otherwise 400, use .../close/ instead. A
                                                          successful DELETE is a soft delete.)
    classrooms/{id}/close/               POST              (teacher only — refunds every active paid
                                                          pass back to its student, then deactivates
                                                          the classroom. Use this instead of DELETE to
                                                          stop running a classroom early.)
    classrooms/{id}/has-access/          GET
    classrooms/{id}/my-pass/             GET               (owner/active/expired/none + expires_at)
    classrooms/{id}/stats/               GET
    classrooms/{id}/share/               POST              (in-app if to_user_id given, else returns a
                                                          web/deep link for outside-the-app sharing)
    classrooms/{id}/share-stats/         GET               (teacher/co-teacher/moderator)
    classrooms/recommended/              GET               (?limit= — personalized by purchase/wishlist
                                                          history, falls back to rating/enrollment)
    coin-purchases/                      GET, POST         (own top-up history)
    coin-purchases/initiate/             POST              (body {"coins": N} — starts a gateway order)
    coin-purchases/{id}/verify/          POST              (gateway checkout callback payload)
    coin-purchases/{id}/retry/           POST              (re-attempt a FAILED purchase)
    schedules/                           GET, POST
    schedules/{id}/                      GET, PUT, PATCH, DELETE
    sessions/                            GET, POST
    sessions/{id}/                       GET, PUT, PATCH, DELETE
    sessions/{id}/join/                  POST
    sessions/{id}/token/                  POST             (fresh token, no participant row — reconnect/testing)
    sessions/{id}/end/                   POST             (teacher/co-teacher/moderator)
    sessions/{id}/kick/{user_id}/        POST             (teacher/co-teacher/moderator)
    sessions/{id}/mute/{user_id}/        POST             (teacher/co-teacher/moderator — force-mutes
                                                          the participant's mic without removing them;
                                                          body {"muted": true|false}, defaults to true)
    sessions/{id}/hand/                  POST             (any active participant — raise/lower OWN
                                                          hand; body {"raised": true|false}, defaults
                                                          to true)
    sessions/{id}/hand/{user_id}/lower/  POST             (teacher/co-teacher/moderator — lower
                                                          someone else's raised hand)
    sessions/{id}/start-recording/       POST             (teacher/co-teacher/moderator — starts a
                                                          LiveKit egress recording; 400 if
                                                          Classroom.recording_enabled is off or a
                                                          recording is already running)
    sessions/{id}/stop-recording/        POST             (teacher/co-teacher/moderator — stops the
                                                          in-progress recording; recording_url fills
                                                          in asynchronously once LiveKit's webhook
                                                          confirms the file is ready)
    sessions/{id}/breakout/             GET, POST        (GET: anyone with room access — current
                                                          breakout layout, [] = none running. POST
                                                          (teacher/co-teacher/moderator):
                                                          {"room_count": int} creates that many empty
                                                          numbered rooms; 400 if a breakout is already
                                                          running — close it first)
    sessions/{id}/breakout/assign/       POST             (teacher/co-teacher/moderator —
                                                          {"participant_id": int, "room": int|null})
    sessions/{id}/breakout/close/        POST             (teacher/co-teacher/moderator — deletes all
                                                          breakout rooms, everyone back in the main room)
    sessions/{id}/engagement-report/     GET              (teacher/co-teacher/moderator only — post-
                                                          session attendance, chat activity, and poll-
                                                          result summary; computed once when the session
                                                          hits COMPLETED, then just read back)
    passes/                              GET, POST
    passes/{id}/                         GET, PUT, PATCH, DELETE  (teacher only. Once a pass has
                                                          ever been purchased: DELETE is refused
                                                          outright (use PATCH is_active=false to
                                                          pause instead — existing holders keep
                                                          access, purchase history stays intact);
                                                          PATCH is refused for any change that would
                                                          retroactively shrink what active holders
                                                          paid for — price can't be raised, and
                                                          validity_days/max_classes/pass_type can't
                                                          be reduced/changed — while at least one
                                                          active, paid purchase is outstanding.)
    join-requests/                       GET, POST      (POST: request to join, on a pass; GET: own
                                                          requests, or ?classroom= as teacher/co-teacher/
                                                          moderator for every request on that classroom,
                                                          optionally + ?status=pending/accepted/rejected/cancelled)
    join-requests/{id}/                  GET
    join-requests/{id}/accept/           POST            (teacher/co-teacher/moderator — charges coins,
                                                          creates the PassPurchase)
    join-requests/{id}/reject/            POST            (teacher/co-teacher/moderator — no charge)
    join-requests/{id}/cancel/            POST            (requesting student only, while still pending)
    pass-purchases/                      GET            (own purchases only by default; ?classroom=<id>
                                                          as that classroom's teacher/co-teacher/
                                                          moderator lists every purchase on it instead)
    pass-purchases/{id}/                 GET
    pass-purchases/{id}/refund/          POST           (classroom's teacher/co-teacher/moderator, or
                                                          platform staff, only — coins back to the
                                                          student, clawed back from the teacher)
    pass-purchases/{id}/toggle-auto-renew/ POST         (body {"auto_renew": true|false} — student's
                                                          own subscription-style opt-in/out; a scheduled
                                                          sweep buys the next PassPurchase automatically
                                                          when this one expires)
    pass-gifts/                          GET, POST      (GET: own gifts, sent AND received; POST: send
                                                          a gift — body {"recipient_id", "class_pass",
                                                          "gift_message"} — coins leave the gifter's
                                                          wallet immediately)
    pass-gifts/{id}/                     GET
    pass-gifts/{id}/claim/                POST           (recipient only, while still pending and not
                                                          expired — this is what actually creates the
                                                          PassPurchase and starts its validity clock)
    pass-gifts/{id}/cancel/               POST           (gifter only, while still pending — refunds
                                                          the gifter's coins)
    participants/                        GET
    participants/{id}/                   GET
    participants/{id}/leave/             POST
    materials/                           GET, POST
    materials/{id}/                      GET, PUT, PATCH, DELETE
    chat-messages/                       GET, POST
    chat-messages/{id}/                  DELETE           (soft delete)
    chat-messages/{id}/react/            POST, DELETE     (Pass 12 — reactions)
    chat-messages/{id}/pin/              POST             (Pass 13)
    chat-messages/{id}/unpin/            POST             (Pass 13)
    chat-message-reports/                GET, POST        (POST: report a message as abusive/spam/etc.,
                                                          body {"message", "reason", "note"} — re-filing
                                                          against the same message updates it rather
                                                          than duplicating; GET: own filed reports, or
                                                          ?session=<id> as that session's teacher/
                                                          co-teacher/moderator/staff for its whole queue)
    chat-message-reports/{id}/review/     POST             (teacher/co-teacher/moderator/staff — body
                                                          {"status": "actioned"|"dismissed"}; actioning
                                                          also soft-deletes the reported message)
    polls/                               GET, POST
    polls/{id}/                          GET, PUT, PATCH, DELETE
    polls/{id}/vote/                     POST
    polls/{id}/close/                    POST
    polls/quick-create/                  POST             (Pass 13 — from a PollTemplate)
    poll-templates/                      GET, POST                          (Pass 13)
    poll-templates/{id}/                 GET, PUT, PATCH, DELETE            (Pass 13)
    sessions/{id}/unread/                GET                                (Pass 13)
    sessions/{id}/mark-read/             POST                               (Pass 13)
    assignments/                         GET, POST
    assignments/{id}/                    GET, PUT, PATCH, DELETE
    submissions/                         GET, POST
    submissions/{id}/                    GET, PUT, PATCH, DELETE
    submissions/{id}/grade/              POST             (teacher only)
    reviews/                             GET, POST
    reviews/{id}/                        GET, PUT, PATCH, DELETE
    wishlist-classrooms/                 GET, POST         (own saved classrooms; POST {"classroom_id": <id>})
    wishlist-classrooms/{id}/            DELETE            (remove from wishlist, own entry only)
    coupons/                             GET, POST
    coupons/{id}/                        GET, PUT, PATCH, DELETE
    coupons/validate/                    GET             (?code= required — checks without spending)
    coin-transactions/                   GET               (own ledger only)
    coin-transactions/balance/           GET               (real User.coin balance)
    withdrawals/                         GET, POST         (GET: own requests, or every request —
                                                          filterable by ?status= — for platform staff;
                                                          POST: request a payout, body {"coins",
                                                          "payout_method", "payout_details"}. Coins are
                                                          debited immediately on request — see
                                                          CoinWithdrawal in models.py. Coin TOP-UP i.e.
                                                          buying coins is a separate, out-of-scope feature.)
    withdrawals/{id}/                    GET
    withdrawals/{id}/cancel/             POST              (own request, only while still pending —
                                                          refunds the coins)
    withdrawals/{id}/approve/            POST              (platform staff only)
    withdrawals/{id}/reject/             POST              (platform staff only; body {"reason": "..."} —
                                                          refunds the coins)
    withdrawals/{id}/mark-paid/          POST              (platform staff only; body
                                                          {"external_reference": "<UTR/UPI txn id>"})
    staff/                               GET, POST
    staff/{id}/                          GET, PUT, PATCH, DELETE
    waitlist/                            GET               (own waitlist entries)
    waitlist/{id}/                       DELETE            (leave the waitlist, own entry only)
    waitlist/{id}/promote/                POST              (teacher/co-teacher/moderator)
    certificates/                        GET, POST         (GET: own, or ?classroom= as teacher/co-teacher/moderator for all issued there; POST: issue one, teacher/co-teacher/moderator only)
    certificates/{id}/                   GET
    reminders/                           GET, POST
    reminders/{id}/                      GET, PUT, PATCH, DELETE
    holidays/                            GET, POST         (?classroom= required for GET)
    holidays/{id}/                       GET, PUT, PATCH, DELETE
    notices/                             GET, POST         (?classroom= required for GET)
    notices/{id}/                        GET, PUT, PATCH, DELETE
    notices/{id}/pin/                    POST              (teacher/co-teacher/moderator)
    queries/                             GET, POST         (student asks a doubt; ?classroom= scopes list)
    queries/{id}/                        GET, PUT, PATCH, DELETE
    queries/{id}/answer/                 POST              (teacher/co-teacher/moderator)
    classroom-reports/                   GET, POST         (POST: file a report on a classroom; GET: own
                                                          reports, or every report — filterable by
                                                          ?classroom= / ?status= — for platform staff)
    classroom-reports/{id}/              GET
    classroom-reports/{id}/review/       POST              (platform staff only — mark
                                                          reviewed/action_taken/dismissed)
    notifications/                       GET               (own notifications, newest first;
                                                          ?is_read=true/false to filter)
    notifications/{id}/                  GET, DELETE       (DELETE clears one, own only)
    notifications/unread-count/          GET               (badge count for the bell icon)
    notifications/{id}/mark-read/        POST              (mark one notification as read)
    notifications/mark-all-read/         POST              (mark every unread notification as read)
    notification-preferences/me/         GET, PATCH        (always the caller's own row — push/email/
                                                          sms/whatsapp_enabled, muted_types, and
                                                          digest_frequency off/daily/weekly; see
                                                          NotificationPreferenceView in views.py)
    referrals/                           GET               (people the caller has successfully referred —
                                                          own ledger only)
    referrals/my-code/                   GET               (own referral code + redemption tally)
    referrals/redeem/                    POST              (redeem someone else's referral code, once,
                                                          new-account-only; body {"code": "R..."})

    livekit-webhook/                     POST              (server-to-server only — point your LiveKit
                                                          project's webhook URL here; see
                                                          LiveKitWebhookView in views.py. Not for
                                                          client/app use.)
    healthz/                             GET               (unauthenticated — DB + cache liveness/
                                                          readiness probe for a load balancer/uptime
                                                          monitor; see HealthCheckView in views.py.
                                                          200 = healthy, 503 = a dependency is down.)

    schema/                               GET               (raw OpenAPI 3 schema, auto-generated by
                                                          drf-spectacular from the ViewSets/serializers
                                                          below — only present once drf-spectacular is
                                                          installed and added to INSTALLED_APPS, see
                                                          the NOTE below.)
    schema/docs/                          GET               (interactive Swagger UI reading from
                                                          schema/ above — same availability caveat.)
"""

from django.urls import include, path
from rest_framework.routers import DefaultRouter

# ---------------------------------------------------------------------------
# NOTE (API docs): drf-spectacular generates a live OpenAPI 3 schema from
# the ViewSets/serializers below — free, always-in-sync documentation
# instead of a hand-maintained Postman collection that silently rots the
# moment an endpoint changes. Wrapped in a try/except so this file still
# imports cleanly even before the package is installed / added to
# INSTALLED_APPS — it degrades to "no docs routes" rather than crashing the
# whole app's URL config.
#
# To actually enable it:
#   1. pip install drf-spectacular
#   2. INSTALLED_APPS += ["drf_spectacular"]
#   3. REST_FRAMEWORK["DEFAULT_SCHEMA_CLASS"] = "drf_spectacular.openapi.AutoSchema"
# ---------------------------------------------------------------------------
try:
    from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

    _SPECTACULAR_AVAILABLE = True
except ImportError:
    _SPECTACULAR_AVAILABLE = False

from .views import (
    AssignmentSubmissionViewSet,
    AssignmentViewSet,
    CertificateViewSet,
    ChatMessageReportViewSet,
    ChatMessageViewSet,
    ClassHolidayViewSet,
    ClassJoinRequestViewSet,
    ClassMaterialViewSet,
    ClassPassViewSet,
    ClassQueryViewSet,
    ClassReminderViewSet,
    ClassScheduleViewSet,
    ClassSessionViewSet,
    ClassroomReportViewSet,
    ClassroomReviewViewSet,
    ClassroomStaffViewSet,
    ClassroomViewSet,
    ClassroomWishlistViewSet,
    CoinPurchaseViewSet,
    CoinTransactionViewSet,
    CoinWithdrawalViewSet,
    CouponViewSet,
    HealthCheckView,
    LiveKitWebhookView,
    LivePollViewSet,
    MyDashboardView,
    NoticeViewSet,
    NotificationPreferenceView,
    NotificationViewSet,
    PassGiftViewSet,
    PassPurchaseViewSet,
    PollTemplateViewSet,
    ReferralViewSet,
    SessionParticipantViewSet,
    SessionWaitlistViewSet,
    StudentProgressView,
    TeacherEarningsView,
)

from . import chunked_upload_views

router = DefaultRouter()
router.register(r"classrooms", ClassroomViewSet, basename="classroom")
router.register(r"classroom-reports", ClassroomReportViewSet, basename="classroomreport")
router.register(r"schedules", ClassScheduleViewSet, basename="classschedule")
router.register(r"sessions", ClassSessionViewSet, basename="classsession")
router.register(r"passes", ClassPassViewSet, basename="classpass")
router.register(r"join-requests", ClassJoinRequestViewSet, basename="classjoinrequest")
router.register(r"pass-purchases", PassPurchaseViewSet, basename="passpurchase")
# NEW (audit fix — "Gifting a pass"): PassGift/PassGiftSerializer already
# existed but had no ViewSet or route wired up anywhere — see
# PassGiftViewSet in views.py.
router.register(r"pass-gifts", PassGiftViewSet, basename="passgift")
# NEW (audit fix — "Per-message chat reports"): ChatMessageReportViewSet
# already existed in views.py but was never registered on the router.
router.register(r"chat-message-reports", ChatMessageReportViewSet, basename="chatmessagereport")
router.register(r"participants", SessionParticipantViewSet, basename="sessionparticipant")
router.register(r"materials", ClassMaterialViewSet, basename="classmaterial")
router.register(r"chat-messages", ChatMessageViewSet, basename="chatmessage")
router.register(r"polls", LivePollViewSet, basename="livepoll")
router.register(r"poll-templates", PollTemplateViewSet, basename="polltemplate")
router.register(r"assignments", AssignmentViewSet, basename="assignment")
router.register(r"submissions", AssignmentSubmissionViewSet, basename="assignmentsubmission")
router.register(r"reviews", ClassroomReviewViewSet, basename="classroomreview")
router.register(r"wishlist-classrooms", ClassroomWishlistViewSet, basename="classroomwishlist")
router.register(r"coupons", CouponViewSet, basename="coupon")
router.register(r"coin-transactions", CoinTransactionViewSet, basename="cointransaction")
router.register(r"coin-purchases", CoinPurchaseViewSet, basename="coinpurchase")
router.register(r"withdrawals", CoinWithdrawalViewSet, basename="coinwithdrawal")
router.register(r"staff", ClassroomStaffViewSet, basename="classroomstaff")
router.register(r"waitlist", SessionWaitlistViewSet, basename="sessionwaitlist")
router.register(r"certificates", CertificateViewSet, basename="certificate")
router.register(r"reminders", ClassReminderViewSet, basename="classreminder")
router.register(r"holidays", ClassHolidayViewSet, basename="classholiday")
router.register(r"notices", NoticeViewSet, basename="notice")
router.register(r"queries", ClassQueryViewSet, basename="classquery")
router.register(r"notifications", NotificationViewSet, basename="notification")
router.register(r"referrals", ReferralViewSet, basename="referral")

urlpatterns = [
    path("dashboard/", MyDashboardView.as_view(), name="my-dashboard"),
    # NOTE (fix — was registered on the router's underlying ViewSet only
    # via import, but TeacherEarningsView is a plain APIView, not a
    # ViewSet, so router.register() never picks it up on its own; it needs
    # its own explicit path() same as dashboard/ and livekit-webhook/
    # above. Without this line the view existed and was imported into
    # urls.py but was unreachable at any URL.
    path("my-earnings/", TeacherEarningsView.as_view(), name="teacher-earnings"),
    # Same "plain APIView needs its own explicit path()" reasoning as
    # my-earnings/ above — StudentProgressView isn't a ViewSet either.
    path("my-progress/", StudentProgressView.as_view(), name="student-progress"),
    # NEW (audit fix — "Per-notification-type channel preferences" +
    # "Digest email"): NotificationPreferenceView already existed as a
    # plain APIView in views.py but, same "APIView needs its own explicit
    # path()" gap as my-earnings/ and my-progress/ above, was never
    # actually reachable at any URL.
    path("notification-preferences/me/", NotificationPreferenceView.as_view(), name="notification-preferences"),
    path("livekit-webhook/", LiveKitWebhookView.as_view(), name="livekit-webhook"),
    # NOTE (production): unauthenticated DB+cache liveness/readiness probe
    # for Render's health check / an uptime monitor / a k8s readiness
    # probe. See HealthCheckView in views.py for exactly what it checks.
    path("healthz/", HealthCheckView.as_view(), name="liveclass-healthz"),
    # --- Chunked upload (large files split into pieces — see
    #     chunked_upload_views.py for why these exist) ---
    path("uploads/chunked/init/", chunked_upload_views.chunked_upload_init, name="chunked-upload-init"),
    path("uploads/chunked/chunk/", chunked_upload_views.chunked_upload_chunk, name="chunked-upload-chunk"),
    path("uploads/chunked/complete/", chunked_upload_views.chunked_upload_complete, name="chunked-upload-complete"),
    path("uploads/chunked/abort/", chunked_upload_views.chunked_upload_abort, name="chunked-upload-abort"),
    path("", include(router.urls)),
]

if _SPECTACULAR_AVAILABLE:
    urlpatterns += [
        path("schema/", SpectacularAPIView.as_view(), name="schema"),
        # Interactive, browsable docs at /liveclass/schema/docs/ — every
        # endpoint above, its params, and its request/response shapes,
        # generated straight from the ViewSets/serializers.
        path(
            "schema/docs/",
            SpectacularSwaggerView.as_view(url_name="schema"),
            name="schema-docs",
        ),
    ]