# Generated by Django 5.2.17 on 2026-09-28 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('test_series', 'Test Series'), ('campus_section', 'Campus Section'), ('engagement', 'App-wide Engagement')], db_index=True, max_length=20)),
                ('scope_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('all_time', 'All Time')], db_index=True, max_length=10)),
                ('period_key', models.CharField(db_index=True, max_length=20)),
                ('score', models.FloatField(default=0)),
                ('rank', models.PositiveIntegerField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['scope_type', 'scope_id', 'period_type', 'period_key', 'rank'], name='leaderboard_scope_t_0265f3_idx'), models.Index(fields=['user', 'period_type'], name='leaderboard_user_id_b2ef69_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope_type', 'scope_id', 'period_type', 'period_key', 'user'), name='unique_leaderboard_row')],
            },
        ),
    ]
