# Generated by Django 6.0.6 on 2026-09-13 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assigmentssubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_assigments_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campus',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campus',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campuses_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='campusanalyticssnapshot',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='campusanalyticssnapshot',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='campus.academicsession'),
        ),
        migrations.AddField(
            model_name='campusparentlink',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='campusparentlink',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_child_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campusparentlink',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_parent_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='digitalidcard',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_id_cards', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='digitalidcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_id_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examterm',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='campus.academicsession'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='campus.feeinvoice'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='campus.academicsession'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='campus.feestructure'),
        ),
        migrations.AddField(
            model_name='notice',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='notice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='campus.department'),
        ),
        migrations.AddField(
            model_name='notice',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_notices_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='campus.academicsession'),
        ),
        migrations.AddField(
            model_name='resultentry',
            name='exam_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='campus.examterm'),
        ),
        migrations.AddField(
            model_name='room',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='campus.department'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='campus.academicsession'),
        ),
        migrations.AddField(
            model_name='notice',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='campus.schoolclass'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='campus.schoolclass'),
        ),
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='campus.schoolclass'),
        ),
        migrations.AddField(
            model_name='notice',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='campus.section'),
        ),
        migrations.AddField(
            model_name='classteacherassigments',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assigments', to='campus.section'),
        ),
        migrations.AddField(
            model_name='campuslivesession',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='campus.section'),
        ),
        migrations.AddField(
            model_name='assigments',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigmentss', to='campus.section'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_staff_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultentry',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_entered', to='campus.staffprofile'),
        ),
        migrations.AddField(
            model_name='classteacherassigments',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_of', to='campus.staffprofile'),
        ),
        migrations.AddField(
            model_name='campuslivesession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions_taught', to='campus.staffprofile'),
        ),
        migrations.AddField(
            model_name='assigments',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigmentss_posted', to='campus.staffprofile'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='campus.section'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='campus.academicsession'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultentry',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='campus.studentenrollment'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='campus.studentenrollment'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='campus.studentenrollment'),
        ),
        migrations.AddField(
            model_name='subject',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='campus.department'),
        ),
        migrations.AddField(
            model_name='resultentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='campus.subject'),
        ),
        migrations.AddField(
            model_name='campuslivesession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='campus.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='campus.subject'),
        ),
        migrations.AddField(
            model_name='assigments',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigmentss', to='campus.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacherassigments',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_made', to='campus.staffprofile'),
        ),
        migrations.AddField(
            model_name='subjectteacherassigments',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_assigmentss', to='campus.section'),
        ),
        migrations.AddField(
            model_name='subjectteacherassigments',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assigmentss', to='campus.staffprofile'),
        ),
        migrations.AddField(
            model_name='subjectteacherassigments',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assigmentss', to='campus.subject'),
        ),
        migrations.AddField(
            model_name='syllabusprogress',
            name='covered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabus_units_covered', to='campus.staffprofile'),
        ),
        migrations.AddField(
            model_name='syllabusunit',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_units', to='campus.section'),
        ),
        migrations.AddField(
            model_name='syllabusunit',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_units', to='campus.academicsession'),
        ),
        migrations.AddField(
            model_name='syllabusunit',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_units', to='campus.subject'),
        ),
        migrations.AddField(
            model_name='syllabusprogress',
            name='syllabus_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='campus.syllabusunit'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='campus.room'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='campus.section'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='campus.academicsession'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='campus.staffprofile'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='campus.subject'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='campus.timeslot'),
        ),
        migrations.AddConstraint(
            model_name='assigmentssubmission',
            constraint=models.UniqueConstraint(fields=('assigments', 'student'), name='campus_unique_submission_per_student'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('campus',), name='one_current_session_per_campus'),
        ),
        migrations.AddIndex(
            model_name='campusanalyticssnapshot',
            index=models.Index(fields=['campus', '-computed_at'], name='campus_camp_campus__3ee7ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='campusparentlink',
            constraint=models.UniqueConstraint(fields=('campus', 'student', 'parent'), name='unique_campus_parent_link'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['invoice', '-created_at'], name='campus_feep_invoice_13140e_idx'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='feepayment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_reference', ''), _negated=True), fields=('gateway_reference',), name='unique_nonblank_gateway_reference'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['session', 'campus'], name='campus_scho_session_d29f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['campus', 'session'], name='campus_fees_campus__c22add_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('school_class', 'name'), name='unique_section_per_class'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['campus', '-created_at'], name='campus_noti_campus__4fa3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['campus', 'role'], name='campus_staf_campus__60b338_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.UniqueConstraint(fields=('campus', 'user'), name='unique_staff_profile_per_campus'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['session', 'status'], name='campus_stud_session_cd8256_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'section', 'session'), name='unique_enrollment_per_section_session'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['enrollment', 'status'], name='campus_feei_enrollm_a77aaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.UniqueConstraint(fields=('enrollment', 'fee_structure'), name='unique_invoice_per_structure'),
        ),
        migrations.AddConstraint(
            model_name='resultentry',
            constraint=models.UniqueConstraint(fields=('enrollment', 'subject', 'exam_term'), name='unique_result_per_exam'),
        ),
        migrations.AddIndex(
            model_name='campuslivesession',
            index=models.Index(fields=['section', 'scheduled_at'], name='campus_camp_section_558977_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['enrollment', 'date'], name='campus_atte_enrollm_c8de09_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('enrollment', 'date', 'subject'), name='unique_attendance_per_day_subject'),
        ),
        migrations.AddIndex(
            model_name='assigments',
            index=models.Index(fields=['section', 'due_date'], name='campus_assi_section_7c6d20_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectteacherassigments',
            constraint=models.UniqueConstraint(fields=('section', 'subject', 'staff'), name='unique_subject_teacher_assigments'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['session', 'time_slot'], name='campus_time_session_25fb71_idx'),
        ),
    ]
