# Generated by Django 6.1.2 on 2026-10-07 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='campus.department'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('principal_hod', 'Principal/HOD'), ('class_teacher', 'Class Teacher'), ('subject_teacher', 'Subject Teacher'), ('moderator', 'Moderator'), ('non_teaching', 'Non-Teaching Staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], db_index=True, default='active', max_length=15),
        ),
        migrations.CreateModel(
            name='CampusAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='campus.campus')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campus', '-created_at'], name='campus_camp_campus__6f8a01_idx'), models.Index(fields=['campus', 'action'], name='campus_camp_campus__7e69e1_idx')],
            },
        ),
    ]
