# Generated by Django 6.1.2 on 2026-10-07 20:51

import common.attachment_validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_t4_campus_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusDoubt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='campus/doubts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=10)),
                ('is_public', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampusDoubtReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='campus/doubts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='class_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='doubts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='doubts_public_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campuslivesession',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], db_index=True, default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='campuslivesession',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], db_index=True, default='offline', max_length=10),
        ),
        migrations.AddIndex(
            model_name='campuslivesession',
            index=models.Index(fields=['status', 'mode', 'scheduled_at'], name='campus_live_reminder_idx'),
        ),
        migrations.AddField(
            model_name='campusdoubt',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_doubts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campusdoubt',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='campusdoubt',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_doubts_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campusdoubt',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='campus.section'),
        ),
        migrations.AddField(
            model_name='campusdoubt',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='campus.academicsession'),
        ),
        migrations.AddField(
            model_name='campusdoubt',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='campus.subject'),
        ),
        migrations.AddField(
            model_name='campusdoubtreply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_doubt_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campusdoubtreply',
            name='doubt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='campus.campusdoubt'),
        ),
        migrations.AddField(
            model_name='timetablereminderlog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='campus.timetableentry'),
        ),
        migrations.AddIndex(
            model_name='campusdoubt',
            index=models.Index(fields=['campus', 'session', '-created_at'], name='campus_camp_campus__d3b6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='campusdoubt',
            index=models.Index(fields=['section', 'subject', 'status'], name='campus_camp_section_0d31f5_idx'),
        ),
        migrations.AddIndex(
            model_name='campusdoubt',
            index=models.Index(fields=['author', '-created_at'], name='campus_camp_author__2683c2_idx'),
        ),
        migrations.AddIndex(
            model_name='campusdoubtreply',
            index=models.Index(fields=['doubt', 'created_at'], name='campus_camp_doubt_i_dd4f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='timetablereminderlog',
            index=models.Index(fields=['occurrence_date'], name='campus_time_occurre_a6bff5_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetablereminderlog',
            constraint=models.UniqueConstraint(fields=('entry', 'occurrence_date'), name='unique_timetable_reminder_per_day'),
        ),
    ]
