# Generated by Django 5.2.17 on 2026-09-28 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earned'), ('purchase', 'Purchased'), ('spend', 'Spent'), ('refund', 'Refunded'), ('gift_sent', 'Gift Sent'), ('gift_received', 'Gift Received'), ('admin_adjustment', 'Admin Adjustment'), ('campus_reward', 'Campus Reward'), ('testseries_purchase', 'Test Series Purchase'), ('testseries_payout', 'Test Series Payout'), ('withdrawal_requested', 'Withdrawal Requested'), ('withdrawal_completed', 'Withdrawal Completed'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('streak_reward', 'Streak Reward')], max_length=20)),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, db_index=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinPurchaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(blank=True, max_length=30)),
                ('gateway_reference', models.CharField(db_index=True, max_length=150)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('gateway_signature', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coins', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_profile.coinledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinWithdrawalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField()),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI')], max_length=20)),
                ('payout_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_profile.coinledger')),
                ('refund_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_profile.coinledger')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_withdrawal_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], default='ACCEPTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relation', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestrictUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restricted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('total_active_days', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_streak'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyRecap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('tests_attempted', models.PositiveIntegerField(default=0)),
                ('classes_attended', models.PositiveIntegerField(default=0)),
                ('posts_liked_received', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_recaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='BlockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_relation', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='block_no_self_block')],
            },
        ),
        migrations.AddIndex(
            model_name='coinledger',
            index=models.Index(fields=['user', '-created_at'], name='user_profil_user_id_94fe04_idx'),
        ),
        migrations.AddIndex(
            model_name='coinledger',
            index=models.Index(fields=['transaction_type', '-created_at'], name='coinledger_type_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='coinledger',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='coinledger_amount_not_zero'),
        ),
        migrations.AddIndex(
            model_name='coinpurchaserequest',
            index=models.Index(fields=['user', '-created_at'], name='user_profil_user_id_ba6605_idx'),
        ),
        migrations.AddIndex(
            model_name='coinpurchaserequest',
            index=models.Index(fields=['status', 'created_at'], name='user_profil_status_55686f_idx'),
        ),
        migrations.AddConstraint(
            model_name='coinpurchaserequest',
            constraint=models.UniqueConstraint(fields=('gateway', 'gateway_reference'), name='unique_gateway_reference_per_gateway'),
        ),
        migrations.AddConstraint(
            model_name='coinpurchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='coinpurchaserequest_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='coinpurchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('coins__gt', 0)), name='coinpurchaserequest_coins_positive'),
        ),
        migrations.AddIndex(
            model_name='coinwithdrawalrequest',
            index=models.Index(fields=['user', '-created_at'], name='user_profil_user_id_7989e7_idx'),
        ),
        migrations.AddIndex(
            model_name='coinwithdrawalrequest',
            index=models.Index(fields=['status', 'created_at'], name='user_profil_status_a65cc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='coinwithdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('coins__gt', 0)), name='coinwithdrawalrequest_coins_positive'),
        ),
        migrations.AddConstraint(
            model_name='coinwithdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount_inr__gt', 0)), name='coinwithdrawalrequest_amount_inr_positive'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'status'], name='user_profil_followe_cbb7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following', 'status'], name='user_profil_followi_3bb82c_idx'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='follow_no_self_follow'),
        ),
        migrations.AddConstraint(
            model_name='restrictuser',
            constraint=models.UniqueConstraint(fields=('user', 'restricted'), name='unique_restrict'),
        ),
        migrations.AddConstraint(
            model_name='restrictuser',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('restricted')), _negated=True), name='restrict_no_self_restrict'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['last_active_date', 'current_streak'], name='user_profil_last_ac_df29f2_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyrecap',
            index=models.Index(fields=['user', '-week_start'], name='user_profil_user_id_ae00da_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklyrecap',
            constraint=models.UniqueConstraint(fields=('user', 'week_start'), name='uniq_weekly_recap_per_user_week'),
        ),
    ]
