# Generated by Django 6.0.6 on 2026-07-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_coins_restrictuser_blockuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='follow',
            name='user_profil_followe_f2a63b_idx',
        ),
        migrations.RemoveIndex(
            model_name='follow',
            name='user_profil_followi_e91fc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='follow',
            name='user_profil_status_98c72c_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='idx_following_status',
            old_name='user_profil_followi_3bb82c_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='idx_follower_status',
            old_name='user_profil_followe_cbb7c0_idx',
        ),
        migrations.AddField(
            model_name='follow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], db_index=True, default='ACCEPTED', max_length=8),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'status', '-created_at'], name='idx_follower_status_created'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following', 'status', '-created_at'], name='idx_following_status_created'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='prevent_self_follow'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='user_follows',
        ),
    ]
