# Generated by Django 6.0.6 on 2026-07-04 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_follow_user_profil_followe_f2a63b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='prevent_self_follow',
        ),
        migrations.RemoveIndex(
            model_name='follow',
            name='idx_follower_status_created',
        ),
        migrations.RemoveIndex(
            model_name='follow',
            name='idx_following_status_created',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='user_profil_followe_cbb7c0_idx',
            old_name='idx_follower_status',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='user_profil_followi_3bb82c_idx',
            old_name='idx_following_status',
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], default='ACCEPTED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower'], name='user_profil_followe_f2a63b_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='user_profil_followi_e91fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['status'], name='user_profil_status_98c72c_idx'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
        migrations.RemoveField(
            model_name='follow',
            name='updated_at',
        ),
    ]
