# Generated by Django 6.0.6 on 2026-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_block_new_accounts_contentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
