# Generated by Django 6.1.2 on 2026-10-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_alter_automoderationflag_id_alter_contentreport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automoderationflag',
            name='source',
            field=models.CharField(choices=[('wordlist', 'Word list / pattern'), ('ai', 'AI model'), ('reports', 'Many user reports')], default='wordlist', max_length=10),
        ),
        migrations.AlterField(
            model_name='automoderationflag',
            name='target_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('story', 'Story'), ('bio', 'Profile bio'), ('message', 'Direct message'), ('feature', 'Feature request'), ('user', 'Account')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment or bullying'), ('hate', 'Hate speech'), ('nudity', 'Nudity or sexual content'), ('violence', 'Violence or dangerous content'), ('self_harm', 'Self-harm'), ('scam', 'Scam or fraud'), ('impersonation', 'Pretending to be someone else'), ('copyright', 'Copyright / intellectual property'), ('other', 'Something else')], max_length=20),
        ),
    ]
