# Generated by Django 5.2.17 on 2026-09-28 15:27

import common.attachment_validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('auto_score', models.PositiveIntegerField(default=0)),
                ('final_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('partially_checked', 'Partially Checked'), ('checked', 'Checked')], db_index=True, default='in_progress', max_length=17)),
                ('roll_number', models.CharField(blank=True, max_length=30)),
                ('enrollment_no', models.CharField(blank=True, max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('draft_answers', models.JSONField(blank=True, default=dict)),
                ('draft_saved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_late', models.BooleanField(default=False)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('integrity_flags', models.PositiveIntegerField(default=0)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testseries_attempts_checked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testseries_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('individual', 'Individual / Marketplace'), ('campus', 'Campus'), ('tuitionclass', 'TuitionClass')], db_index=True, max_length=20)),
                ('context_type', models.CharField(blank=True, max_length=20, null=True)),
                ('context_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('price_coins', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10)),
                ('attempts_allowed', models.PositiveIntegerField(default=1)),
                ('subject', models.CharField(blank=True, db_index=True, max_length=60)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=6)),
                ('delivery_mode', models.CharField(choices=[('self_paced', 'Self paced'), ('scheduled', 'Scheduled window'), ('live', 'Live (video)')], db_index=True, default='self_paced', max_length=12)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('late_entry_minutes', models.PositiveSmallIntegerField(default=0)),
                ('proctoring', models.CharField(choices=[('off', 'Off'), ('camera', 'Camera (recorded)')], default='off', max_length=8)),
                ('record_live', models.BooleanField(default=True)),
                ('pass_percentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('certificate_enabled', models.BooleanField(default=False)),
                ('certificate_title', models.CharField(blank=True, max_length=200)),
                ('result_release', models.CharField(choices=[('instant', 'Instantly after checking'), ('after_end', 'After the test window ends'), ('manual', 'When the creator releases them')], default='instant', max_length=10)),
                ('results_released_at', models.DateTimeField(blank=True, null=True)),
                ('show_solutions', models.BooleanField(default=True)),
                ('share_slug', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testseries_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('live_session', 'Live session'), ('proctor', 'Proctoring')], db_index=True, max_length=12)),
                ('room_name', models.CharField(max_length=80)),
                ('egress_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='recording', max_length=10)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='testseries.testattempt')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='testseries.testseries')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestLiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], db_index=True, default='scheduled', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testseries_live_hosted', to=settings.AUTH_USER_MODEL)),
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_session', to='testseries.testseries')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('percentage', models.FloatField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=200)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='testseries.testattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testseries_certificates', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='testseries.testseries')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddField(
            model_name='testattempt',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='testseries.testseries'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('text', 'Text / Subjective'), ('mcq', 'Multiple Choice (single)'), ('msq', 'Multiple Select'), ('list', 'List-based (match / order)')], db_index=True, max_length=4)),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='testseries/questions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('marks', models.PositiveIntegerField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(blank=True, default=dict)),
                ('negative_marks', models.PositiveIntegerField(default=0)),
                ('topic', models.CharField(blank=True, max_length=80)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=6)),
                ('explanation', models.TextField(blank=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testseries.testseries')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestSeriesPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coins_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('escrowed', 'Escrowed'), ('released', 'Released'), ('refunded', 'Refunded')], db_index=True, default='escrowed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='testseries.testattempt')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testseries_purchases', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='testseries.testseries')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSeriesReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='testseries.testattempt')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='testseries.testseries')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testseries_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_data', models.JSONField(default=dict)),
                ('answer_attachment', models.FileField(blank=True, null=True, upload_to='testseries/answers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('is_auto_graded', models.BooleanField()),
                ('is_correct', models.BooleanField(null=True)),
                ('marks_awarded', models.PositiveIntegerField(blank=True, null=True)),
                ('penalty', models.PositiveIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewer_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='testseries.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testseries_responses_reviewed', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='testseries.testattempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_response_per_attempt_question')],
            },
        ),
        migrations.CreateModel(
            name='TestProctorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('app_background', 'App sent to background'), ('tab_switch', 'Switched app / tab'), ('face_missing', 'Face not visible'), ('multiple_faces', 'Multiple faces'), ('camera_off', 'Camera turned off'), ('network_drop', 'Network dropped'), ('other', 'Other')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_events', to='testseries.testattempt')),
            ],
            options={
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['attempt', 'event_type'], name='ts_pev_attempt_type_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='testseries',
            index=models.Index(fields=['source', 'context_type', 'context_id'], name='testseries__source_90ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='testseries',
            index=models.Index(fields=['creator', 'status'], name='testseries__creator_5632ca_idx'),
        ),
        migrations.AddIndex(
            model_name='testseries',
            index=models.Index(fields=['status', 'subject', 'difficulty'], name='testseries__status_47aa80_idx'),
        ),
        migrations.AddIndex(
            model_name='testrecording',
            index=models.Index(fields=['series', 'kind'], name='ts_rec_series_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='testcertificate',
            constraint=models.UniqueConstraint(fields=('series', 'student'), name='unique_certificate_per_student_series'),
        ),
        migrations.AddConstraint(
            model_name='testattempt',
            constraint=models.UniqueConstraint(fields=('series', 'student', 'attempt_number'), name='unique_attempt_per_student_series_number'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('series', 'order')},
        ),
        migrations.AddConstraint(
            model_name='testseriesreview',
            constraint=models.UniqueConstraint(fields=('series', 'student'), name='unique_review_per_student_per_series'),
        ),
    ]
