# Generated by Django 6.0.6 on 2026-09-13 19:57

import common.attachment_validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('individual', 'Individual / Marketplace'), ('campus', 'Campus'), ('liveclass', 'LiveClass')], db_index=True, max_length=10)),
                ('context_type', models.CharField(blank=True, max_length=20, null=True)),
                ('context_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('price_coins', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10)),
                ('attempts_allowed', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testseries_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('auto_score', models.PositiveIntegerField(default=0)),
                ('final_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('partially_checked', 'Partially Checked'), ('checked', 'Checked')], db_index=True, default='in_progress', max_length=17)),
                ('roll_number', models.CharField(blank=True, max_length=30)),
                ('enrollment_no', models.CharField(blank=True, max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testseries_attempts_checked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testseries_attempts', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='testseries.testseries')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('text', 'Text / Subjective'), ('mcq', 'Multiple Choice (single)'), ('msq', 'Multiple Select'), ('list', 'List-based (match / order)')], db_index=True, max_length=4)),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='testseries/questions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('marks', models.PositiveIntegerField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(blank=True, default=dict)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testseries.testseries')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestSeriesPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coins_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('escrowed', 'Escrowed'), ('released', 'Released'), ('refunded', 'Refunded')], db_index=True, default='escrowed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='testseries.testattempt')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testseries_purchases', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='testseries.testseries')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSeriesReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='testseries.testattempt')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='testseries.testseries')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testseries_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_data', models.JSONField(default=dict)),
                ('answer_attachment', models.FileField(blank=True, null=True, upload_to='testseries/answers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('is_auto_graded', models.BooleanField()),
                ('is_correct', models.BooleanField(null=True)),
                ('marks_awarded', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewer_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='testseries.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testseries_responses_reviewed', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='testseries.testattempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_response_per_attempt_question')],
            },
        ),
        migrations.AddIndex(
            model_name='testseries',
            index=models.Index(fields=['source', 'context_type', 'context_id'], name='testseries__source_90ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='testseries',
            index=models.Index(fields=['creator', 'status'], name='testseries__creator_5632ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='testattempt',
            constraint=models.UniqueConstraint(fields=('series', 'student'), name='unique_attempt_per_student_per_series'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('series', 'order')},
        ),
        migrations.AddConstraint(
            model_name='testseriesreview',
            constraint=models.UniqueConstraint(fields=('series', 'student'), name='unique_review_per_student_per_series'),
        ),
    ]
