# Generated by Django 5.2.17 on 2026-09-28 15:27

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tuitionclass.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('attendance', 'Attendance'), ('fee_or_pass', 'Fee / Pass'), ('leave_request', 'Leave request'), ('technical_issue', 'Technical issue'), ('callback_request', 'Request a callback'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(help_text="Short label shown in the template picker, e.g. 'My child will be absent today'.", max_length=120)),
                ('body_template', models.TextField(help_text='The exact sentence sent to the teacher. May use {child_name} and {classroom_title} placeholders — both filled in server-side, never from user input.')),
                ('requires_session', models.BooleanField(default=False, help_text="If set, the sender must also pick one of the classroom's own sessions (e.g. 'About today's class') — a closed choice, never free text.")),
                ('is_active', models.BooleanField(default=True, help_text='Retire a template without deleting it — past messages that used it keep their resolved_message snapshot either way (see ParentTeacherMessage.template, on_delete=PROTECT).')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_type', models.CharField(choices=[('individual', 'Individual'), ('organisation', 'Organisation')], default='individual', max_length=20)),
                ('organisation_name', models.CharField(blank=True, help_text="Required when classroom_type is 'organisation'.", max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='classroom_covers/', validators=[tuitionclass.models.MaxFileSizeValidator(5)])),
                ('language', models.CharField(blank=True, default='English', max_length=50)),
                ('whiteboard_enabled', models.BooleanField(default=True)),
                ('screen_share_enabled', models.BooleanField(default=True)),
                ('chat_enabled', models.BooleanField(default=True)),
                ('recording_enabled', models.BooleanField(default=True)),
                ('captions_enabled', models.BooleanField(default=False)),
                ('max_participants', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('enrolled_count', models.PositiveIntegerField(default=0, help_text='Distinct students currently holding an active, unexpired pass.')),
                ('share_count', models.PositiveIntegerField(default=0, help_text='Total number of times this classroom has been shared, any channel.')),
                ('referral_enabled', models.BooleanField(default=False, help_text='When on, any authenticated user can generate a shareable referral link for this classroom (see classrooms/{id}/refer-link/) and earn a daily commission on any pass purchase that comes in through it.')),
                ('referral_commission_percent', models.DecimalField(decimal_places=2, default=0, help_text="% of each day's released class-earning charge (see PassPurchase.charge_for_session) that gets paid to whoever referred the student — deducted OUT OF the teacher's own share, never added on top by the platform. The teacher sets this rate themselves and funds it out of their own earnings. Only takes effect while referral_enabled=True.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_trial_enabled', models.BooleanField(default=False)),
                ('trial_password', models.CharField(blank=True, default='', max_length=128)),
                ('trial_duration_minutes', models.PositiveSmallIntegerField(default=5, help_text='How many minutes a trial join stays valid (1-30).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('parents_enabled', models.BooleanField(default=False)),
                ('attendance_min_percent', models.PositiveSmallIntegerField(default=50, help_text='Minimum % of a session a student must attend to count as present (1-100).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('attendance_edit_days', models.PositiveSmallIntegerField(default=7, help_text='Days after a session during which its attendance can still be edited by hand.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('chat_group_enabled', models.BooleanField(default=False)),
                ('linked_conversation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_teaching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type', models.CharField(choices=[('free', 'Free'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price in coins (User.coin). 0 = free pass.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('validity_days', models.PositiveIntegerField(help_text='How many days this pass stays valid after purchase', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_classes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_gifting', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='tuitionclass.classroom')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', validators=[tuitionclass.models.MaxFileSizeValidator(10), django.core.validators.FileExtensionValidator(['pdf'])])),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tuitionclass.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_bans_issued', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='tuitionclass.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomParentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('skipped', 'Skipped'), ('invited', 'Invited')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_states', to='tuitionclass.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_parent_states', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', 'Scam / took coins, no class'), ('not_delivering', 'Classes not happening as promised'), ('inappropriate', 'Inappropriate content or behaviour'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tuitionclass.classroom')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tuitionclass.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('copy_link', 'Copy Link'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tuitionclass.classroom')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_shares_made', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('co_teacher', 'Co-Teacher'), ('moderator', 'Moderator'), ('ta', 'Teaching Assistant')], default='ta', max_length=15)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tuitionclass.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='tuitionclass.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_type', models.CharField(choices=[('specific_date', 'Specific Date'), ('daily', 'Daily'), ('weekday', 'Weekdays (Mon-Fri)'), ('weekend', 'Weekends (Sat-Sun)'), ('weekly', 'Weekly (custom days)'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tuitionclass.classroom')),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, help_text="e.g. 'Diwali', 'Teacher on leave'", max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays_created', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tuitionclass.classroom')),
                ('schedule', models.ForeignKey(blank=True, help_text='Leave blank to mark this date off across every schedule in the classroom.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tuitionclass.classschedule')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('recording_url', models.URLField(blank=True)),
                ('egress_id', models.CharField(blank=True, max_length=64)),
                ('whiteboard_snapshot', models.JSONField(blank=True, null=True)),
                ('spotlight_identity', models.CharField(blank=True, max_length=64)),
                ('caption_status', models.CharField(choices=[('none', 'Not Requested'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=12)),
                ('caption_url', models.URLField(blank=True)),
                ('transcription_job_name', models.CharField(blank=True, max_length=128)),
                ('engagement_report', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tuitionclass.classroom')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tuitionclass.classschedule')),
            ],
            options={
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomTrialAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=5)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_accesses', to='tuitionclass.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_trials', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_accesses', to='tuitionclass.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='ClassReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField()),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='push', max_length=10)),
                ('is_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reminders', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tuitionclass.classsession')),
            ],
            options={
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered')], default='open', max_length=10)),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries_answered', to=settings.AUTH_USER_MODEL)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries_asked', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='tuitionclass.classroom')),
                ('session', models.ForeignKey(blank=True, help_text='Optional — set if the doubt is about a specific live session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='tuitionclass.classsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('ppt', 'Presentation'), ('doc', 'Document'), ('image', 'Image'), ('video', 'Video'), ('link', 'External Link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='class_materials/', validators=[tuitionclass.models.MaxFileSizeValidator(100), django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'mp4', 'mov', 'webm', 'zip'])])),
                ('external_link', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='tuitionclass.classroom')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='tuitionclass.classsession')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flagged_reason', models.CharField(blank=True, max_length=100)),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='tuitionclass.chatmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='tuitionclass.classsession')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakoutRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_rooms', to='tuitionclass.classsession')),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='assigments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assigmentss/', validators=[tuitionclass.models.MaxFileSizeValidator(50), django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'mp4', 'mov', 'webm', 'zip'])])),
                ('due_date', models.DateTimeField()),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigmentss', to='tuitionclass.classroom')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigmentss', to='tuitionclass.classsession')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='CoinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField()),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('gateway_signature', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='tuitionclass.coinpurchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('reason', models.CharField(choices=[('pass_purchase', 'Pass Purchase'), ('class_earning', 'Class Earning'), ('referral_bonus', 'Referral Bonus'), ('class_referral_commission', 'Class Referral Commission'), ('class_referral_join_bonus', 'Class Referral Join Bonus'), ('refund', 'Refund'), ('gift_sent', 'Pass Gifted To Someone'), ('gift_cancelled_refund', 'Unclaimed Gift Refunded'), ('pass_auto_renewed', 'Pass Auto-Renewed'), ('admin_adjustment', 'Admin Adjustment'), ('topup', 'Wallet Top-up'), ('withdrawal', 'Withdrawal'), ('withdrawal_reversed', 'Withdrawal Reversed')], max_length=32)),
                ('amount', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField()),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI')], max_length=20)),
                ('payout_details', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_withdrawals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='tuitionclass.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='tuitionclass.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional auto-hide time, e.g. for a one-off exam-date notice.', null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='tuitionclass.classroom')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitionclass_notices_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentTeacherMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_message', models.TextField(editable=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('responded', 'Responded')], default='open', max_length=10)),
                ('teacher_reply', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages', to='tuitionclass.classroom')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_messages_replied', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='Set only when the chosen template has requires_session=True.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_messages', to='tuitionclass.classsession')),
                ('template', models.ForeignKey(help_text='PROTECT, not CASCADE/SET_NULL: a template must never be hard-deleted while any sent message still references it — retire it via is_active instead.', on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='tuitionclass.parentmessagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('coin_wallet', 'Coin Wallet'), ('free', 'Free')], default='coin_wallet', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coins_spent', models.PositiveIntegerField(default=0)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('classes_attended', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('per_day_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('coins_released', models.PositiveIntegerField(default=0)),
                ('last_charge_date', models.DateField(blank=True, null=True)),
                ('refunded_amount', models.PositiveIntegerField(default=0)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('referral_commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('referral_per_day_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('referral_coins_released', models.PositiveIntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_failed_at', models.DateTimeField(blank=True, null=True)),
                ('class_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tuitionclass.classpass')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='tuitionclass.coupon')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_purchases', to=settings.AUTH_USER_MODEL)),
                ('renewed_from', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_into', to='tuitionclass.passpurchase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='PassGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_spent', models.PositiveIntegerField(help_text="Frozen at gift time — the class_pass's price then.")),
                ('gift_message', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Claim'), ('claimed', 'Claimed'), ('cancelled', 'Cancelled By Gifter'), ('expired', 'Expired Unclaimed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('class_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='tuitionclass.classpass')),
                ('gifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_gifted', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_gifted_to_me', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_gift', to='tuitionclass.passpurchase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassDailyCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('referral_amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_charges', to='tuitionclass.classsession')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_charges', to='tuitionclass.passpurchase')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClassJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('message', models.CharField(blank=True, help_text='Optional note from the student to the teacher.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_join_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_join_requests', to=settings.AUTH_USER_MODEL)),
                ('class_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='tuitionclass.classpass')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='tuitionclass.classroom')),
                ('pass_purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_request', to='tuitionclass.passpurchase')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_index', models.PositiveSmallIntegerField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tuitionclass.livepoll')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_templates', to='tuitionclass.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_poll_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_used', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused')], max_length=10)),
                ('source', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('minutes_present', models.PositiveIntegerField(default=0)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='tuitionclass.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_log', to='tuitionclass.classsession')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_captions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host/Teacher'), ('student', 'Student')], default='student', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('kicked_at', models.DateTimeField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('hand_raised_at', models.DateTimeField(blank=True, null=True)),
                ('breakout_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='tuitionclass.breakoutroom')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tuitionclass.classsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('thumbs_up', '👍'), ('heart', '❤️'), ('laugh', '😂'), ('clap', '👏'), ('party', '🎉'), ('raised_hands', '🙌')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_log', to='tuitionclass.classsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_chat_message_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_seen_poll_id', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='tuitionclass.classsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_read_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='tuitionclass.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlisted_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=100)),
                ('attendance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('homework_completion_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='tuitionclass.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='assigmentsSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assigments_submissions/', validators=[tuitionclass.models.MaxFileSizeValidator(50), django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'mp4', 'mov', 'webm', 'zip'])])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assigments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tuitionclass.assigments')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitionclass_assigments_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assigments', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='tuitionclass.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['read_at'],
                'indexes': [models.Index(fields=['message'], name='tuitionclas_message_1707b1_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('abusive', 'Abusive / Harassment'), ('spam', 'Spam / Advertising'), ('off_topic', 'Off-topic'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tuitionclass.chatmessage')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='tuitionclas_status_dc77c1_idx')],
                'unique_together': {('message', 'reporter')},
            },
        ),
        migrations.CreateModel(
            name='ChatReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('thumbs_up', '👍'), ('heart', '❤️'), ('laugh', '😂')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='tuitionclass.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['message'], name='tuitionclas_message_7bf46d_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('cover_image', 'Classroom Cover Image'), ('material', 'Class Material'), ('assigments_attachment', 'assigments Attachment'), ('submission_file', 'assigments Submission File')], max_length=30)),
                ('original_file_name', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=10)),
                ('total_chunks', models.PositiveIntegerField()),
                ('total_size', models.PositiveBigIntegerField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('aborted', 'Aborted'), ('expired', 'Expired')], default='in_progress', max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='tuitionclas_status_346744_idx'), models.Index(fields=['user', 'status'], name='tuitionclas_user_id_f5399e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['teacher', 'is_active'], name='tuitionclas_teacher_4cbf10_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['-rating_avg'], name='tuitionclas_rating__3e95e3_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['language'], name='tuitionclas_languag_b99845_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['classroom_type'], name='tuitionclas_classro_36e758_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_deleted'], name='tuitionclas_is_dele_4c4023_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='classroom_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=django.contrib.postgres.indexes.GinIndex(fields=['subject'], name='classroom_subject_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='classroom_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('classroom', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='classroomban',
            unique_together={('classroom', 'student')},
        ),
        migrations.AddIndex(
            model_name='classroomparentstate',
            index=models.Index(fields=['classroom', 'status'], name='parentstate_cls_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomparentstate',
            unique_together={('classroom', 'student')},
        ),
        migrations.AddIndex(
            model_name='classroomreport',
            index=models.Index(fields=['classroom', 'status'], name='tuitionclas_classro_b50252_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('classroom', 'reported_by'), name='one_pending_report_per_user_per_classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomreview',
            unique_together={('classroom', 'student')},
        ),
        migrations.AddIndex(
            model_name='classroomshare',
            index=models.Index(fields=['classroom', '-created_at'], name='tuitionclas_classro_ea3377_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomshare',
            index=models.Index(fields=['shared_by', '-created_at'], name='tuitionclas_shared__f82f53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomstaff',
            unique_together={('classroom', 'user')},
        ),
        migrations.AddIndex(
            model_name='classroomwishlist',
            index=models.Index(fields=['user', '-created_at'], name='tuitionclas_user_id_075d90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomwishlist',
            unique_together={('user', 'classroom')},
        ),
        migrations.AddIndex(
            model_name='classholiday',
            index=models.Index(fields=['classroom', 'date'], name='tuitionclas_classro_363fa7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classholiday',
            unique_together={('classroom', 'schedule', 'date')},
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['classroom', 'status', 'scheduled_start'], name='tuitionclas_classro_ac0a78_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomtrialaccess',
            index=models.Index(fields=['ended_at', 'expires_at'], name='trial_ended_expires_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomtrialaccess',
            unique_together={('classroom', 'user')},
        ),
        migrations.AddIndex(
            model_name='classreminder',
            index=models.Index(fields=['remind_at', 'is_sent'], name='tuitionclas_remind__dcf47e_idx'),
        ),
        migrations.AddIndex(
            model_name='classquery',
            index=models.Index(fields=['classroom', 'status', '-created_at'], name='tuitionclas_classro_28cc60_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'sent_at'], name='tuitionclas_session_c1ec81_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_flagged'], name='tuitionclas_is_flag_040e0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breakoutroom',
            unique_together={('session', 'room_number')},
        ),
        migrations.AddIndex(
            model_name='coinpurchase',
            index=models.Index(fields=['user', 'status', '-created_at'], name='tuitionclas_user_id_21e6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='coinwithdrawal',
            index=models.Index(fields=['status', 'requested_at'], name='tuitionclas_status_0a45d3_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['classroom', 'is_pinned', '-created_at'], name='tuitionclas_classro_abd12c_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['classroom', 'expires_at'], name='tuitionclas_classro_821f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='parentteachermessage',
            index=models.Index(fields=['classroom', 'status', '-created_at'], name='tuitionclas_classro_57a74e_idx'),
        ),
        migrations.AddIndex(
            model_name='parentteachermessage',
            index=models.Index(fields=['sender', '-created_at'], name='tuitionclas_sender__0572b0_idx'),
        ),
        migrations.AddIndex(
            model_name='passpurchase',
            index=models.Index(fields=['student', 'status', 'expires_at'], name='tuitionclas_student_7957fd_idx'),
        ),
        migrations.AddIndex(
            model_name='passpurchase',
            index=models.Index(fields=['referred_by'], name='tuitionclas_referre_df700f_idx'),
        ),
        migrations.AddIndex(
            model_name='passpurchase',
            index=models.Index(fields=['auto_renew', 'status', 'expires_at'], name='tuitionclas_auto_re_950640_idx'),
        ),
        migrations.AddIndex(
            model_name='passgift',
            index=models.Index(fields=['recipient', 'status'], name='tuitionclas_recipie_b4d5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='passgift',
            index=models.Index(fields=['status', 'expires_at'], name='tuitionclas_status_b7f31f_idx'),
        ),
        migrations.AddConstraint(
            model_name='passdailycharge',
            constraint=models.UniqueConstraint(fields=('purchase', 'date'), name='one_charge_per_purchase_per_day'),
        ),
        migrations.AddIndex(
            model_name='classjoinrequest',
            index=models.Index(fields=['classroom', 'status'], name='tuitionclas_classro_3735a5_idx'),
        ),
        migrations.AddIndex(
            model_name='classjoinrequest',
            index=models.Index(fields=['student', 'status'], name='tuitionclas_student_e7d391_idx'),
        ),
        migrations.AddConstraint(
            model_name='classjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('classroom', 'student'), name='one_pending_join_request_per_student_per_classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='pollresponse',
            unique_together={('poll', 'student')},
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['student', 'status'], name='attendance_student_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'student')},
        ),
        migrations.AddIndex(
            model_name='sessioncaption',
            index=models.Index(fields=['session', 'created_at'], name='tuitionclas_session_393a43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'user', 'joined_at')},
        ),
        migrations.AddIndex(
            model_name='sessionreaction',
            index=models.Index(fields=['session', 'created_at'], name='tuitionclas_session_ca083d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionreadstate',
            unique_together={('session', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionwaitlist',
            unique_together={('session', 'student')},
        ),
        migrations.AddIndex(
            model_name='studentreportcard',
            index=models.Index(fields=['classroom', 'student'], name='tuitionclas_classro_53c040_idx'),
        ),
    ]
