# Generated by Django 6.1.2 on 2026-10-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionclass', '0003_referral_attribution_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='chat_group_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
