# Generated by Django 6.1.2 on 2026-10-09 21:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyrightClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimant_name', models.CharField(max_length=120)),
                ('claimant_email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, default='', max_length=120)),
                ('is_rights_owner', models.BooleanField(default=True)),
                ('target_type', models.CharField(choices=[('post', 'Post / reel'), ('story', 'Story')], max_length=10)),
                ('target_id', models.CharField(max_length=64)),
                ('content_snapshot', models.CharField(blank=True, default='', max_length=300)),
                ('work_description', models.TextField(max_length=2000)),
                ('original_work_url', models.URLField(blank=True, default='', max_length=500)),
                ('infringement_details', models.TextField(blank=True, default='', max_length=2000)),
                ('good_faith_statement', models.BooleanField(default=False)),
                ('accuracy_statement', models.BooleanField(default=False)),
                ('signature', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('needs_info', 'Waiting for claimant'), ('under_review', 'Under review'), ('upheld', 'Upheld - content removed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by claimant'), ('countered', 'Counter-notice filed'), ('restored', 'Content restored')], db_index=True, default='submitted', max_length=14)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=6)),
                ('source', models.CharField(choices=[('user', 'Filed by a rights holder'), ('report', 'Raised from user reports'), ('staff', 'Filed by staff')], default='user', max_length=8)),
                ('required_level', models.PositiveSmallIntegerField(default=1)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('bad_faith', models.BooleanField(db_index=True, default=False)),
                ('needs_info_message', models.CharField(blank=True, default='', max_length=500)),
                ('info_requested_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_claims_filed', to=settings.AUTH_USER_MODEL)),
                ('content_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_claims_received', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='copyrights.copyrightclaim')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_claims_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('review_claim', 'L1: can review claims (reject, ask for info, notes)'), ('uphold_claim', 'L2: can uphold claims, remove content, issue strikes, restore content'), ('revoke_strike', 'L3: can revoke strikes and reverse decisions'), ('terminate_account', 'L3: can terminate / reinstate accounts for repeat infringement')],
            },
        ),
        migrations.CreateModel(
            name='CopyrightAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(default='system', max_length=40)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit', to='copyrights.copyrightclaim')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyrightCounterNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(max_length=2000)),
                ('good_faith_statement', models.BooleanField(default=False)),
                ('jurisdiction_consent', models.BooleanField(default=False)),
                ('signature', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('waiting', 'Waiting period running'), ('court_action', 'Claimant reported court action'), ('restored', 'Restored'), ('rejected', 'Rejected by staff')], db_index=True, default='waiting', max_length=14)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('restore_after', models.DateTimeField(db_index=True)),
                ('court_action_note', models.TextField(blank=True, default='', max_length=1000)),
                ('court_action_reported_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter_notice', to='copyrights.copyrightclaim')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyright_counter_notices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CopyrightStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_strikes', models.PositiveSmallIntegerField(default=0)),
                ('level', models.CharField(choices=[('good', 'Good standing'), ('warning', 'Warning (1 strike)'), ('restricted', 'Uploads blocked (2 strikes)'), ('review', 'Termination review (3+ strikes)'), ('terminated', 'Terminated')], db_index=True, default='good', max_length=10)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copyright_standing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'copyright standings',
            },
        ),
        migrations.CreateModel(
            name='CopyrightStrike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=255)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strike', to='copyrights.copyrightclaim')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyright_strikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyrightTakedown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=10)),
                ('target_id', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('held', 'On hold (temporary)'), ('removed', 'Removed'), ('restored', 'Restored')], db_index=True, default='held', max_length=10)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('auto_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='takedown', to='copyrights.copyrightclaim')),
            ],
        ),
        migrations.AddIndex(
            model_name='copyrightclaim',
            index=models.Index(fields=['status', '-created_at'], name='cr_claim_status_idx'),
        ),
        migrations.AddIndex(
            model_name='copyrightclaim',
            index=models.Index(fields=['target_type', 'target_id'], name='cr_claim_target_idx'),
        ),
        migrations.AddIndex(
            model_name='copyrightclaim',
            index=models.Index(fields=['claimant', '-created_at'], name='cr_claim_claimant_idx'),
        ),
        migrations.AddIndex(
            model_name='copyrightstrike',
            index=models.Index(fields=['user', 'revoked_at', 'expires_at'], name='cr_strike_user_idx'),
        ),
        migrations.AddIndex(
            model_name='copyrighttakedown',
            index=models.Index(fields=['target_type', 'target_id', 'state'], name='cr_takedown_target_idx'),
        ),
    ]
