# Generated by Django 6.0.6 on 2026-09-13 19:57

import common.attachment_validators
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assigments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('personal', 'Personal'), ('campus', 'Campus'), ('liveclass', 'LiveClass')], db_index=True, max_length=10)),
                ('context_type', models.CharField(blank=True, max_length=20)),
                ('context_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assigments/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('has_structured_questions', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='assigmentsAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_data', models.JSONField(default=dict)),
                ('answer_attachment', models.FileField(blank=True, null=True, upload_to='assigments/answer_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('is_auto_graded', models.BooleanField()),
                ('is_correct', models.BooleanField(null=True)),
                ('marks_awarded', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewer_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='assigmentsQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('text', 'Text / Subjective'), ('mcq', 'Multiple Choice (single answer)'), ('msq', 'Multiple Select (multiple answers)'), ('list', 'List / Ordered Items')], db_index=True, max_length=4)),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assigments/question_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('marks', models.PositiveIntegerField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='assigmentsSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('written_content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='assigments/submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), common.attachment_validators.validate_attachment_size])),
                ('roll_number', models.CharField(blank=True, max_length=30)),
                ('enrollment_no', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('submitted', 'Submitted'), ('late', 'Late'), ('partially_checked', 'Partially Checked'), ('checked', 'Checked')], db_index=True, default='missing', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('total_marks_awarded', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('public_slug', models.CharField(blank=True, max_length=40)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
