# Generated by Django 6.0.6 on 2026-09-13 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assigments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assigments',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_assigmentss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assigmentsanswer',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assigments_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assigmentsquestion',
            name='assigments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assigments.assigments'),
        ),
        migrations.AddField(
            model_name='assigmentsanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assigments.assigmentsquestion'),
        ),
        migrations.AddField(
            model_name='assigmentssubmission',
            name='assigments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assigments.assigments'),
        ),
        migrations.AddField(
            model_name='assigmentssubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigments_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assigmentsanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assigments.assigmentssubmission'),
        ),
        migrations.AddIndex(
            model_name='assigments',
            index=models.Index(fields=['source', 'context_type', 'context_id'], name='assigments__source_6545fc_idx'),
        ),
        migrations.AddIndex(
            model_name='assigments',
            index=models.Index(fields=['posted_by', 'due_date'], name='assigments__posted__f16dfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='assigmentsquestion',
            constraint=models.UniqueConstraint(fields=('assigments', 'order'), name='unique_question_order_per_assigments'),
        ),
        migrations.AddIndex(
            model_name='assigmentssubmission',
            index=models.Index(fields=['assigments', 'status'], name='assigments__assigme_33be3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='assigmentssubmission',
            constraint=models.UniqueConstraint(fields=('assigments', 'student'), name='unique_submission_per_student'),
        ),
        migrations.AddConstraint(
            model_name='assigmentssubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('public_slug', ''), _negated=True), fields=('public_slug',), name='unique_nonblank_public_slug'),
        ),
        migrations.AddConstraint(
            model_name='assigmentsanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_answer_per_submission_question'),
        ),
    ]
